//! Z3 Solver FFI Bridge & Execution Engine.
//!
//! This module provides a robust interface to Z3 for solving SMT-LIB2 scripts
//! generated by the lowering engine. It supports incremental solving, model
//! extraction, unsat core extraction, and resource limits.

#[cfg(feature = "z3")]
use crate::config::{Logic, SolverConfig};
#[cfg(feature = "z3")]
use crate::error::{SolverError, VerifyError};
#[cfg(feature = "z3")]
use crate::model::{Model, UnsatCore};
#[cfg(feature = "z3")]
use crate::smtlib::Script;
#[cfg(feature = "z3")]
use std::collections::HashMap;
#[cfg(feature = "z3")]
use std::sync::{Arc, Mutex};
#[cfg(feature = "z3")]
use std::time::{Duration, Instant};

/// Process-global lock serializing ALL interaction with the z3 C library.
///
/// The z3-sys C build is not configured with thread-safety, and
/// `z3::Context::thread_local()` mutates shared context parameters per solve
/// (`logic`, `timeout`, `random_seed`, ...). When `cargo test` runs the
/// obligation suite across many threads at once, concurrent `verify()` calls
/// corrupt the parser and make well-formed scripts fail to load
/// ("holds 0 assertion(s) but the script declares N"), which surfaces as a
/// flaky `ParseError` under parallelism (often NOT in isolation). Locking every
/// solve makes every result deterministic under any test parallelism, while
/// keeping the `naso-verify` CLI correct: CLI invocations are separate processes,
/// so this lock only affects in-process parallelism (tests / the library).
#[cfg(feature = "z3")]
static Z3_SERIALIZE: Mutex<()> = Mutex::new(());

/// Verification result from the solver.
#[cfg(feature = "z3")]
#[derive(Debug, Clone)]
pub enum VerifyResult {
    /// Satisfiable with a model.
    Sat(Model),
    /// Unsatisfiable with optional unsat core.
    Unsat(Option<UnsatCore>),
    /// Unknown (incomplete theory, timeout, etc.).
    Unknown(String),
    /// Error during solving.
    Error(String),
}

impl VerifyResult {
    pub fn is_sat(&self) -> bool {
        matches!(self, VerifyResult::Sat(_))
    }

    pub fn is_unsat(&self) -> bool {
        matches!(self, VerifyResult::Unsat(_))
    }

    pub fn is_unknown(&self) -> bool {
        matches!(self, VerifyResult::Unknown(_))
    }

    pub fn is_error(&self) -> bool {
        matches!(self, VerifyResult::Error(_))
    }

    pub fn model(&self) -> Option<&Model> {
        match self {
            VerifyResult::Sat(m) => Some(m),
            _ => None,
        }
    }

    pub fn unsat_core(&self) -> Option<&UnsatCore> {
        match self {
            VerifyResult::Unsat(Some(core)) => Some(core),
            _ => None,
        }
    }
}
#[cfg(feature = "z3")]
/// Z3 solver wrapper with context management.
#[cfg(feature = "z3")]
pub struct Solver {
    config: SolverConfig,
    context: Option<z3::Context>,
    solver: Option<z3::Solver>,
    incremental_level: u32,
    assertion_ids: HashMap<String, usize>, // Named assertions for unsat core
    next_assertion_id: usize,
}
#[cfg(feature = "z3")]
impl Solver {
    /// Create a new solver with the given configuration.
    pub fn new(config: SolverConfig) -> Result<Self, VerifyError> {
        let ctx = Self::create_context(&config)?;
        let solver = Self::create_solver(&ctx, &config)?;

        Ok(Self {
            config,
            context: Some(ctx),
            solver: Some(solver),
            incremental_level: 0,
            assertion_ids: HashMap::new(),
            next_assertion_id: 0,
        })
    }

    /// Create Z3 context with configuration.
    fn create_context(config: &SolverConfig) -> Result<z3::Context, VerifyError> {
        // Use thread-local context and configure it
        let mut ctx = z3::Context::thread_local();

        // Set logic
        ctx.update_param_value("logic", config.logic.as_str());

        // Set timeout
        ctx.update_param_value("timeout", &config.timeout.as_millis().to_string());

        // Set memory limit (advisory)
        ctx.update_param_value("memory_limit", &config.memory_mb.to_string());

        // Set random seed for reproducibility
        if let Some(seed) = config.seed {
            ctx.update_param_value("random_seed", &seed.to_string());
        }

        // Set number of threads
        if config.threads > 0 {
            ctx.update_param_value("parallel.enable", "true");
            ctx.update_param_value("parallel.threads_max", &config.threads.to_string());
        }

        // Enable model generation
        ctx.update_param_value(
            "model",
            if config.produce_models {
                "true"
            } else {
                "false"
            },
        );

        // Enable unsat core generation
        ctx.update_param_value(
            "unsat_core",
            if config.produce_unsat_cores {
                "true"
            } else {
                "false"
            },
        );

        Ok(ctx)
    }

    /// Create Z3 solver from context.
    fn create_solver(
        _ctx: &z3::Context,
        _config: &SolverConfig,
    ) -> Result<z3::Solver, VerifyError> {
        // Use a fresh solver for each check if not incremental
        // Logic is set via SMT-LIB2 (set-logic) in the script, not via API
        let solver = z3::Solver::new();

        Ok(solver)
    }

    /// Assert a formula (by name for unsat core tracking).
    pub fn assert_named(&mut self, name: &str, formula: &z3::ast::Bool) -> Result<(), VerifyError> {
        let solver = self.solver.as_mut().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?;

        let id = self.next_assertion_id;
        self.next_assertion_id += 1;
        self.assertion_ids.insert(name.to_string(), id);

        solver.assert(formula);
        Ok(())
    }

    /// Assert a formula without name.
    pub fn assert(&mut self, formula: &z3::ast::Bool) -> Result<(), VerifyError> {
        let solver = self.solver.as_mut().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?;

        solver.assert(formula);
        Ok(())
    }

    /// Push a new incremental level.
    pub fn push(&mut self) -> Result<(), VerifyError> {
        let solver = self.solver.as_mut().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?;

        solver.push();
        self.incremental_level += 1;
        Ok(())
    }

    /// Pop the current incremental level.
    pub fn pop(&mut self, n: u32) -> Result<(), VerifyError> {
        let solver = self.solver.as_mut().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?;

        if n > self.incremental_level {
            return Err(VerifyError::Solver(SolverError::IncrementalError(format!(
                "Cannot pop {} levels (current depth: {})",
                n, self.incremental_level
            ))));
        }

        solver.pop(n);
        self.incremental_level -= n;
        Ok(())
    }

    /// Check satisfiability with optional assumptions.
    pub fn check_sat(
        &mut self,
        assumptions: &[z3::ast::Bool],
    ) -> Result<VerifyResult, VerifyError> {
        let solver = self.solver.as_mut().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?;

        let start = Instant::now();
        let timeout = self.config.timeout;

        // Check with timeout
        let result = if assumptions.is_empty() {
            solver.check()
        } else {
            solver.check_assumptions(assumptions)
        };

        let elapsed = start.elapsed();
        if elapsed >= timeout {
            return Ok(VerifyResult::Unknown(format!(
                "Timeout after {:.2}s",
                elapsed.as_secs_f64()
            )));
        }

        match result {
            z3::SatResult::Sat => {
                let model = if self.config.produce_models {
                    Model::from_z3(solver.get_model())
                        .map_err(|e| VerifyError::Solver(SolverError::ModelExtractionFailed(e)))?
                } else {
                    Model::empty()
                };
                Ok(VerifyResult::Sat(model))
            }
            z3::SatResult::Unsat => {
                let unsat_core = if self.config.produce_unsat_cores {
                    let core = solver.get_unsat_core();
                    if core.is_empty() {
                        None
                    } else {
                        Some(UnsatCore::from_z3(core, &self.assertion_ids).map_err(|e| {
                            VerifyError::Solver(SolverError::UnsatCoreExtractionFailed(e))
                        })?)
                    }
                } else {
                    None
                };
                Ok(VerifyResult::Unsat(unsat_core))
            }
            z3::SatResult::Unknown => {
                let reason = solver
                    .get_reason_unknown()
                    .map(|s| s.to_string())
                    .unwrap_or_else(|| "Unknown reason".to_string());
                Ok(VerifyResult::Unknown(reason))
            }
        }
    }

    /// Get the Z3 context.
    pub fn context(&self) -> Option<&z3::Context> {
        self.context.as_ref()
    }

    /// Get the Z3 solver.
    pub fn solver(&self) -> Option<&z3::Solver> {
        self.solver.as_ref()
    }

    /// Reset the solver (clear all assertions).
    pub fn reset(&mut self) -> Result<(), VerifyError> {
        let ctx = self.context.as_ref().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Context not initialized".to_string(),
            ))
        })?;

        let solver = Self::create_solver(ctx, &self.config)?;
        self.solver = Some(solver);
        self.incremental_level = 0;
        self.assertion_ids.clear();
        self.next_assertion_id = 0;
        Ok(())
    }
}
#[cfg(feature = "z3")]
/// Parse and execute an SMT-LIB2 script using Z3.
#[cfg(feature = "z3")]
pub fn verify(smt_script: &str, config: SolverConfig) -> Result<VerifyResult, VerifyError> {
    // Serialize all z3 interaction: see `Z3_SERIALIZE` (z3-sys is not thread-safe here,
    // and concurrent solves corrupt the parser under cargo-test parallelism).
    let _z3_guard = Z3_SERIALIZE.lock().unwrap_or_else(|e| e.into_inner());
    let mut solver = Solver::new(config)?;

    // Parse SMT-LIB2 script using high-level API
    let inner = solver.solver.as_mut().ok_or_else(|| {
        VerifyError::Solver(SolverError::ContextFailed(
            "Solver not initialized".to_string(),
        ))
    })?;

    // Remember what the script CLAIMS, before handing it to Z3.
    let (claimed_assertions, final_depth) = scan_script(smt_script);

    // A script whose parentheses never balance cannot be a well-formed SMT-LIB command
    // sequence. Check this BEFORE calling Z3, because Z3 recovers from the imbalance by
    // discarding text from the unclosed paren onward -- and in that case the discarded
    // region swallows the assertions, so both the script and Z3 agree the solver holds
    // none. A count-based check then passes, and Z3 reports `sat` for an empty solver.
    // Measured, not assumed: for an unbalanced `declare-fun`, the scanner and
    // `get_assertions()` both reported 0.
    if final_depth != 0 {
        return Err(VerifyError::Solver(SolverError::ParseError(format!(
            "unbalanced parentheses in the SMT-LIB script: {final_depth} unclosed `(` at \
             end of input. The script was never valid, so no obligation was checked. This \
             is an emitter bug -- fix it rather than reading the result."
        ))));
    }

    inner.from_string(smt_script);

    // `Solver::from_string` returns `()` and DISCARDS Z3's error code. A script Z3 cannot
    // parse is silently dropped, and the solver then reports `sat` for a solver holding NO
    // assertions at all.
    //
    // That is not a degraded answer, it is a wrong one. A verification driver asks "does
    // this obligation hold?"; for a discarded script the honest answer is "this was never
    // checked", and `sat` says the opposite. An obligation is proved by finding NO model
    // satisfying its negation, so a discarded script makes the driver report the negation
    // SAT -- i.e. REFUTED -- for a claim that was never sent anywhere. A false negative
    // stacked on a false positive, and entirely silent.
    //
    // Two real bugs hid here before this check existed: a `declare-const` carrying a
    // function sort, and a `declare-fun` with a dropped closing paren. Both were
    // indistinguishable from correct behaviour.
    //
    // So: count what Z3 actually holds, and refuse to answer if it disagrees with what the
    // script asked for.
    let loaded_assertions = inner.get_assertions().len();
    if loaded_assertions != claimed_assertions {
        return Err(VerifyError::Solver(SolverError::ParseError(format!(
            "Z3 rejected the script: it holds {loaded_assertions} assertion(s) but the \
             script declares {claimed_assertions}. A script Z3 cannot parse is discarded \
             silently, so this obligation was never checked. Fix the emitter rather than \
             reading the result."
        ))));
    }

    // Check satisfiability
    solver.check_sat(&[])
}

/// Count the `assert` commands a script declares, at nesting depth zero.
///
/// Only depth zero counts: `(assert ...)` inside a `(check-sat-and-exit)` body or any other
/// enclosing command belongs to that command, not to the solver's top-level assertion set.
/// Z3's `get_assertions()` likewise reports only what `assert` added to the solver.
///
/// Parenthesis tracking is string-aware so a `;` comment containing an unmatched paren
/// cannot corrupt the depth. SMT-LIB strings are rare in generated scripts but a `|...|`
/// quoted symbol may contain both parens and semicolons, so both are skipped.
#[cfg_attr(not(test), allow(dead_code))]
fn count_top_level_asserts(script: &str) -> usize {
    scan_script(script).0
}

/// Split a script into (top-level `assert` count, final paren depth).
///
/// The depth is returned because counting alone is NOT sufficient to detect a discarded
/// script. Verified against Z3 with an unbalanced `declare-fun` whose closing paren was
/// dropped: the script scanner and `get_assertions()` both reported ZERO assertions, so they
/// agreed, the count-based check passed, and Z3 went on to answer `sat` for a solver holding
/// nothing. The unclosed paren swallowed the assertion in both readings. A depth of
/// non-zero at end-of-script is therefore its own malformed-script signal.
fn scan_script(script: &str) -> (usize, usize) {
    let bytes = script.as_bytes();
    let mut i = 0;
    let mut depth = 0usize;
    let mut count = 0usize;

    while i < bytes.len() {
        match bytes[i] {
            // Comment to end of line.
            b';' => {
                while i < bytes.len() && bytes[i] != b'\n' {
                    i += 1;
                }
            }
            // Quoted symbol: may contain anything except an unescaped bar.
            b'|' => {
                i += 1;
                while i < bytes.len() && bytes[i] != b'|' {
                    i += 1;
                }
                i += 1;
            }
            // Double-quoted string literal: skip to the closing quote, honouring escapes.
            b'"' => {
                i += 1;
                while i < bytes.len() && bytes[i] != b'"' {
                    // SMT-LIB2 uses doubled quotes to escape a quote inside a string.
                    if bytes[i] == b'"' && i + 1 < bytes.len() && bytes[i + 1] == b'"' {
                        i += 1;
                    }
                    i += 1;
                }
                i += 1;
            }
            b'(' => {
                depth += 1;
                // A command starts with a symbol right after `(`. If that symbol is
                // `assert`, this paren opens a top-level assertion.
                if depth == 1 {
                    let rest = &script[i + 1..];
                    let word: String = rest
                        .chars()
                        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_' || *c == '-')
                        .collect();
                    if word == "assert" {
                        count += 1;
                    }
                }
                i += 1;
            }
            b')' => {
                depth = depth.saturating_sub(1);
                i += 1;
            }
            _ => i += 1,
        }
    }

    (count, depth)
}
#[cfg(feature = "z3")]
/// Execute multiple independent verification conditions in parallel.
#[cfg(feature = "z3")]
pub fn verify_parallel(
    scripts: Vec<(String, String)>, // (name, script)
    config: SolverConfig,
) -> Vec<(String, Result<VerifyResult, VerifyError>)> {
    use rayon::prelude::*;

    scripts
        .into_par_iter()
        .map(|(name, script)| {
            let result = verify(&script, config.clone());
            (name, result)
        })
        .collect()
}
#[cfg(feature = "z3")]
/// Solver statistics.
#[cfg(feature = "z3")]
#[derive(Debug, Clone, Default)]
pub struct SolverStats {
    pub total_time: Duration,
    pub sat_calls: usize,
    pub unsat_calls: usize,
    pub unknown_calls: usize,
    pub error_calls: usize,
    pub total_assertions: usize,
}
#[cfg(feature = "z3")]
impl SolverStats {
    pub fn record(&mut self, result: &VerifyResult, elapsed: Duration) {
        self.total_time += elapsed;
        match result {
            VerifyResult::Sat(_) => self.sat_calls += 1,
            VerifyResult::Unsat(_) => self.unsat_calls += 1,
            VerifyResult::Unknown(_) => self.unknown_calls += 1,
            VerifyResult::Error(_) => self.error_calls += 1,
        }
    }
}

#[cfg(all(test, feature = "z3"))]
mod guard_tests {
    use super::*;

    /// A malformed script must be REFUSED, not answered.
    ///
    /// This is the regression for the silent-discard failure. `(declare-const f (Int) Int)`
    /// is invalid SMT-LIB2 -- a `declare-const` takes a plain sort, and `(Int) Int` is the
    /// range-sort notation for a function. Z3 rejects the script and `from_string` swallows
    /// the error, so before this guard the result was `Sat` for a solver holding no
    /// assertions: the driver reported the obligation REFUTED for a claim never sent to Z3.
    #[test]
    fn a_malformed_declaration_is_an_error_not_a_sat() {
        let bad = "(set-logic UFLIA)\n\
                   (declare-const f (Int) Int)\n\
                   (assert (not (= (f 0) (f 0))))\n\
                   (check-sat)\n(exit)\n";
        let result = verify(bad, SolverConfig::default());
        assert!(
            matches!(result, Err(VerifyError::Solver(SolverError::ParseError(_)))),
            "a discarded script must be a ParseError, got {result:?}"
        );
    }

    /// An unbalanced parenthesis must also be refused. This is the second real bug: the
    /// `declare-fun` emitter once dropped a closing paren.
    #[test]
    fn an_unbalanced_script_is_an_error_not_a_sat() {
        // NOTE the missing `)` after the `Int` sort -- exactly the emitter bug.
        let bad = "(set-logic UFLIA)\n\
                   (declare-fun f ((Int)) Int\n\
                   (assert (not (= (f 0) (f 0))))\n\
                   (check-sat)\n(exit)\n";
        let result = verify(bad, SolverConfig::default());
        assert!(
            matches!(result, Err(VerifyError::Solver(SolverError::ParseError(_)))),
            "an unbalanced script must be a ParseError, got {result:?}"
        );
    }

    /// A VALID function-sorted declaration must still work -- the guard must not simply
    /// reject everything mentioning a function.
    #[test]
    fn a_valid_function_declaration_is_still_accepted() {
        let good = "(set-logic UFLIA)\n\
                    (declare-fun f ((Int)) Int)\n\
                    (assert (not (= (f 0) (f 0))))\n\
                    (check-sat)\n(exit)\n";
        let result = verify(good, SolverConfig::default());
        assert!(
            result.is_ok(),
            "a valid function declaration must be accepted, got {result:?}"
        );
        assert!(
            result.as_ref().unwrap().is_unsat(),
            "the tautology's negation is unsatisfiable, so the obligation is PROVED; got {result:?}"
        );
    }

    /// The control: a script Z3 parses must produce a real answer, not an error.
    #[test]
    fn a_well_formed_script_is_answered_normally() {
        let good = "(set-logic UFLIA)\n(assert (not (= 1 1)))\n(check-sat)\n(exit)\n";
        let r = verify(good, SolverConfig::default()).expect("valid script");
        assert!(r.is_unsat(), "got {r:?}");
    }

    #[test]
    fn counts_top_level_asserts() {
        assert_eq!(count_top_level_asserts("(assert (> 1 0))"), 1);
        assert_eq!(
            count_top_level_asserts("(assert (> 1 0))\n(assert (< 0 1))"),
            2
        );
        assert_eq!(count_top_level_asserts("(set-logic UFLIA)\n"), 0);

        // `(push 1)` CLOSES before the assert, so the assert really is at depth 1 -- and Z3
        // agrees, loading 1 assertion. An earlier version of this test asserted 0 here,
        // reasoning the assert was "nested inside another command". It was not, and the
        // error was in the direction that would hide a genuinely discarded assertion.
        assert_eq!(count_top_level_asserts("(push 1)\n(assert (> 1 0))"), 1);

        // An assert that really is nested inside an unclosed command is not top level.
        assert_eq!(count_top_level_asserts("(build (assert (> 1 0))"), 0);
    }

    #[test]
    fn reports_unbalanced_parentheses() {
        assert_eq!(scan_script("(assert (> 1 0))\n"), (1, 0));
        assert_eq!(scan_script("(assert (> 1 0))\n(assert (< 0 1))\n"), (2, 0));
        // The emitter bug that motivated this: a `declare-fun` missing its closing paren.
        assert_eq!(
            scan_script("(declare-fun f ((Int)) Int\n(assert (> 1 0))\n"),
            (0, 1)
        );
    }

    /// An assert swallowed by an unclosed command is dropped by Z3 AND by the scanner, so
    /// the count check cannot see it -- only the balance check can. This is the measured
    /// reason counting alone was insufficient.
    #[test]
    fn a_swallowed_assertion_is_caught_only_by_the_balance_check() {
        let bad = "(set-logic UFLIA)\n\
                   (declare-fun f ((Int)) Int\n\
                   (assert (not (= (f 0) (f 0))))\n\
                   (check-sat)\n(exit)\n";
        let (claimed, depth) = scan_script(bad);
        assert_eq!(claimed, 0, "the scanner sees zero assertions here too");
        assert_ne!(depth, 0, "so only the balance check can catch this");
        assert!(
            matches!(
                verify(bad, SolverConfig::default()),
                Err(VerifyError::Solver(SolverError::ParseError(_)))
            ),
            "must be refused, not answered"
        );
    }

    #[test]
    fn ignores_assertions_inside_comments_and_strings() {
        // A comment mentioning `assert` must not be counted.
        assert_eq!(count_top_level_asserts("; (assert (> 1 0))\n"), 0);
        // A quoted symbol may legally contain the word assert.
        assert_eq!(count_top_level_asserts("|assert (x)|\n"), 0);
        // A real assertion after either must still be found.
        assert_eq!(
            count_top_level_asserts("; (assert (> 1 0))\n(assert (> 1 0))"),
            1
        );
        assert_eq!(count_top_level_asserts("|assert (x)|\n(assert (> 1 0))"), 1);
    }
}
