//! Straight-line WGSL code generation.
//!
//! This is the deliberately narrow WGSL backend. It handles straight-line code
//! -- let bindings, assignments, arithmetic, comparisons, the numeric builtins
//! the prelude declares, and casts -- and produces a `fn` per Naso function.
//!
//! # Why this is separate from [`super::wgsl`]
//!
//! The existing generator works from PIR and dispatches on two hardcoded
//! function names, `quantize_int8_symmetric` and `dequantize_int8_symmetric`.
//! Anything else becomes a `// Unknown call` comment in the output: a silent
//! no-op where the user asked for a shader. That is the failure mode this
//! module exists to avoid, so here every construct that is not handled is a
//! `CodegenError` naming the construct and its span.
//!
//! # Why no loops
//!
//! Loops require polyhedral loop lowering, which is not implemented --
//! `lower_affine_expr` in the LLVM path returns only the constant and discards
//! every coefficient. Rather than emit a shader that silently runs the body
//! once, `for` / `forall` / `while` are rejected with a message that says so.
//! A parallel `forall` does not have a correct lowering, so refusing is the
//! only sound option.
//!
//! The practical effect: a WGSL `fn` is generated, but not a compute pipeline
//! entry point. Dispatching over a tensor is not expressible without the loop
//! lowering. That is stated at the call site rather than hidden.

use crate::ast::{
    BinOp, Expr, ExprKind, Function, Item, Literal, Program, Stmt, StmtKind, TypeKind,
};
use crate::codegen::error::{CodegenError, CodegenResult};
use std::collections::{HashMap, HashSet};

/// Lower a program to WGSL.
///
/// Errors rather than emitting a partial shader: any function containing a
/// construct this backend does not implement aborts the whole emission.
pub fn generate_wgsl_straight_line(program: &Program) -> CodegenResult<String> {
    let mut out = String::new();
    out.push_str("// Generated by Naso -- straight-line WGSL backend\n");
    out.push_str("// Loops are not lowered yet; functions containing them are rejected.\n\n");

    // Names of every function in the program, so a call to one can be
    // reported as such rather than as an unknown callee.
    let function_names: Vec<String> = program
        .items
        .iter()
        .filter_map(|i| match i {
            Item::Function(f) => Some(f.name.name.clone()),
            _ => None,
        })
        .collect();

    // Signatures, so a call can be arity- and return-checked.
    let signatures: Vec<(&str, usize, bool)> = program
        .items
        .iter()
        .filter_map(|i| match i {
            Item::Function(f) => Some((f.name.name.as_str(), f.params.len(), f.ret_ty.is_some())),
            _ => None,
        })
        .collect();

    // Reject the WHOLE program before emitting anything, so a failure never
    // leaves a truncated shader on disk.
    for item in &program.items {
        let Item::Function(func) = item else {
            return Err(CodegenError::UnsupportedFeature(format!(
                "straight-line WGSL only supports function definitions, found \
                 {} at line {}",
                describe_item(item),
                item_span_line(item)
            )));
        };
        check_supported(func, &function_names, &signatures)?;
    }

    // WGSL has no forward declarations: a function must be declared before it
    // is called. Emitting in source order is therefore wrong whenever a caller
    // precedes its callee, so emit in dependency order.
    let order = emission_order(program)?;
    for func in &order {
        emit_function(&mut out, func)?;
    }

    if order.is_empty() {
        return Err(CodegenError::UnsupportedFeature(
            "no function definitions to lower to WGSL".to_string(),
        ));
    }
    Ok(out)
}

/// Order functions so every callee is emitted before its callers.
///
/// DFS post-order over the call graph. A cycle means the program is recursive,
/// which WGSL cannot express (no forward declarations, no mutual recursion);
/// that is reported rather than emitted in an arbitrary order that would fail
/// to compile with a confusing WGSL error.
fn emission_order(program: &Program) -> CodegenResult<Vec<&Function>> {
    let functions: Vec<&Function> = program
        .items
        .iter()
        .filter_map(|i| match i {
            Item::Function(f) => Some(f),
            _ => None,
        })
        .collect();

    // Index by name for lookup.
    let by_name: HashMap<&str, &Function> = functions
        .iter()
        .map(|f| (f.name.name.as_str(), *f))
        .collect();

    let mut order: Vec<&Function> = Vec::with_capacity(functions.len());
    // "done" guards against re-emitting; "on_stack" detects cycles.
    let mut done: HashSet<&str> = HashSet::new();
    let mut on_stack: Vec<&str> = Vec::new();

    // Explicit stack to avoid deep recursion on a long call chain.
    for root in &functions {
        if done.contains(root.name.name.as_str()) {
            continue;
        }
        let mut work: Vec<(&str, bool)> = vec![(root.name.name.as_str(), false)];
        while let Some((name, expanded)) = work.pop() {
            if expanded {
                on_stack.retain(|n| *n != name);
                if done.insert(name)
                    && let Some(f) = by_name.get(name)
                {
                    order.push(f);
                }
                continue;
            }
            if done.contains(name) {
                continue;
            }
            if on_stack.contains(&name) {
                return Err(CodegenError::UnsupportedFeature(format!(
                    "recursive call to `{name}` is not supported: WGSL has no \
                     forward declarations, so a callee must be emitted before \
                     its caller. Mutual recursion has no valid WGSL form."
                )));
            }
            on_stack.push(name);
            work.push((name, true));
            // Push callees first so they are visited (and emitted) first.
            if let Some(f) = by_name.get(name) {
                let mut callees = vec![];
                collect_called_names(f, &by_name, &mut callees);
                for c in callees.into_iter().rev() {
                    if !done.contains(c) {
                        work.push((c, false));
                    }
                }
            }
        }
    }
    Ok(order)
}

/// Gather names of functions called by `func`.
///
/// Written as a plain recursive function rather than a closure: a closure
/// cannot call itself, and threading `&mut impl FnMut` through every arm fights
/// the borrow checker for no benefit.
fn collect_called_names<'a>(
    func: &Function,
    by_name: &HashMap<&'a str, &'a Function>,
    out: &mut Vec<&'a str>,
) {
    for stmt in &func.body.stmts {
        collect_called_names_stmt(stmt, by_name, out);
    }
    if let Some(e) = &func.body.expr {
        collect_called_names_expr(e, by_name, out);
    }
}

fn collect_called_names_stmt<'a>(
    st: &Stmt,
    by_name: &HashMap<&'a str, &'a Function>,
    out: &mut Vec<&'a str>,
) {
    match &st.kind {
        StmtKind::Let(s) => collect_called_names_expr(&s.value, by_name, out),
        StmtKind::LetInOut(s) => collect_called_names_expr(&s.value, by_name, out),
        StmtKind::LetConsume(s) => collect_called_names_expr(&s.value, by_name, out),
        StmtKind::Expr(e) | StmtKind::Return(Some(e)) => collect_called_names_expr(e, by_name, out),
        _ => {}
    }
}

fn collect_called_names_expr<'a>(
    e: &Expr,
    by_name: &HashMap<&'a str, &'a Function>,
    out: &mut Vec<&'a str>,
) {
    match &e.kind {
        ExprKind::Call(callee, args) => {
            if let ExprKind::Var(v) = &callee.kind
                && let Some(target) = by_name.get(v.name.as_str())
            {
                out.push(target.name.name.as_str());
            }
            collect_called_names_expr(callee, by_name, out);
            for a in args {
                collect_called_names_expr(a, by_name, out);
            }
        }
        ExprKind::Binary(_, l, r) => {
            collect_called_names_expr(l, by_name, out);
            collect_called_names_expr(r, by_name, out);
        }
        ExprKind::Unary(_, i) | ExprKind::Ascribe(i, _) | ExprKind::Index(i, _) => {
            collect_called_names_expr(i, by_name, out)
        }
        ExprKind::Assign(l, r) => {
            collect_called_names_expr(l, by_name, out);
            collect_called_names_expr(r, by_name, out);
        }
        ExprKind::Return(Some(i)) | ExprKind::Break(Some(i)) => {
            collect_called_names_expr(i, by_name, out)
        }
        ExprKind::Block(b) => {
            for st in &b.stmts {
                collect_called_names_stmt(st, by_name, out);
            }
            if let Some(e) = &b.expr {
                collect_called_names_expr(e, by_name, out);
            }
        }
        _ => {}
    }
}

/// Reject any function containing a construct this backend cannot emit.
fn check_supported(
    func: &Function,
    function_names: &[String],
    signatures: &[(&str, usize, bool)],
) -> CodegenResult<()> {
    let known_function_names: Vec<&str> = function_names.iter().map(|s| s.as_str()).collect();
    for stmt in &func.body.stmts {
        check_stmt(stmt, &known_function_names, signatures)?;
    }
    if let Some(tail) = &func.body.expr {
        check_expr(tail, &known_function_names, signatures)?;
    }
    Ok(())
}

fn check_stmt(
    stmt: &Stmt,
    known_function_names: &[&str],
    signatures: &[(&str, usize, bool)],
) -> CodegenResult<()> {
    match &stmt.kind {
        StmtKind::Let(s) => check_expr(&s.value, known_function_names, signatures)?,
        StmtKind::LetInOut(s) => check_expr(&s.value, known_function_names, signatures)?,
        StmtKind::LetConsume(s) => check_expr(&s.value, known_function_names, signatures)?,
        StmtKind::Expr(e) => check_expr(e, known_function_names, signatures)?,
        StmtKind::Return(e) => {
            if let Some(e) = e {
                check_expr(e, known_function_names, signatures)?;
            }
        }
        // Proof blocks are erased: they produce no runtime code and so
        // correctly contribute nothing to the shader.
        StmtKind::Proof(_) => {}
        other => {
            return Err(CodegenError::UnsupportedFeature(format!(
                "statement `{other}` at line {} is not supported by the \
                 straight-line WGSL backend",
                stmt.span.line
            )));
        }
    }
    Ok(())
}

fn check_expr(
    expr: &Expr,
    known_function_names: &[&str],
    signatures: &[(&str, usize, bool)],
) -> CodegenResult<()> {
    match &expr.kind {
        ExprKind::Literal(_) | ExprKind::Var(_) | ExprKind::Index(..) => Ok(()),
        ExprKind::Block(b) => {
            for s in &b.stmts {
                check_stmt(s, known_function_names, signatures)?;
            }
            if let Some(e) = &b.expr {
                check_expr(e, known_function_names, signatures)?;
            }
            Ok(())
        }
        ExprKind::Assign(lhs, rhs) => {
            check_expr(lhs, known_function_names, signatures)?;
            check_expr(rhs, known_function_names, signatures)
        }
        ExprKind::Ascribe(inner, _) => check_expr(inner, known_function_names, signatures),
        // `return` is an expression in this AST, and `naso parse` shows it
        // under ExprKind::Return rather than StmtKind::Return.
        ExprKind::Return(inner) => {
            if let Some(e) = inner {
                check_expr(e, known_function_names, signatures)?;
            }
            Ok(())
        }
        ExprKind::Break(inner) => {
            if let Some(e) = inner {
                check_expr(e, known_function_names, signatures)?;
            }
            Ok(())
        }
        ExprKind::Continue => Ok(()),
        ExprKind::Call(callee, args) => {
            check_expr(callee, known_function_names, signatures)?;
            for a in args {
                check_expr(a, known_function_names, signatures)?;
            }
            let name = callee_name(callee);
            if builtin_from_name(&name).is_some() {
                return Ok(());
            }

            // A call to another function in this program. WGSL supports this;
            // the emitter orders callees before callers so no forward
            // declaration is needed. The signature is checked here so a
            // mismatch is a diagnostic rather than invalid WGSL.
            if let Some((_, arity, returns_value)) = signatures.iter().find(|(n, _, _)| *n == name)
            {
                if args.len() != *arity {
                    return Err(CodegenError::InstructionError(format!(
                        "call to `{name}` at line {} passes {} argument(s) but \
                         it takes {arity}",
                        expr.span.line,
                        args.len()
                    )));
                }
                // A unit-returning callee used for a value has no WGSL form:
                // `f()` where f is `fn f()` yields nothing to assign.
                if !returns_value
                    && matches!(
                        &expr.kind,
                        ExprKind::Binary(..) | ExprKind::Index(..) | ExprKind::Call(..)
                    )
                {
                    return Err(CodegenError::InstructionError(format!(
                        "`{name}` at line {} returns no value but is used as one",
                        expr.span.line
                    )));
                }
                return Ok(());
            }

            Err(unsupported_expr(expr))
        }
        ExprKind::Binary(op, lhs, rhs) => {
            if wgsl_binop(op).is_none() {
                return Err(CodegenError::UnsupportedFeature(format!(
                    "operator `{op:?}` at line {} has no WGSL lowering",
                    expr.span.line
                )));
            }
            check_expr(lhs, known_function_names, signatures)?;
            check_expr(rhs, known_function_names, signatures)
        }
        ExprKind::Unary(op, inner) => {
            if wgsl_unop(op).is_none() {
                return Err(CodegenError::UnsupportedFeature(format!(
                    "unary operator `{op:?}` at line {} has no WGSL lowering",
                    expr.span.line
                )));
            }
            check_expr(inner, known_function_names, signatures)
        }
        _ => Err(unsupported_expr(expr)),
    }
}

fn unsupported_expr(expr: &Expr) -> CodegenError {
    let kind = match &expr.kind {
        ExprKind::Forall(_) => "forall loop",
        ExprKind::For(_) => "for loop",
        ExprKind::While(..) => "while loop",
        ExprKind::Match(..) => "match",
        ExprKind::If(..) => "if",
        ExprKind::Quantified(_) => "quantified proposition (proof-only, outside a proof block)",
        _ => "expression",
    };
    let why = if kind.contains("loop") {
        "Loops need polyhedral lowering, which is not implemented; emitting a \
         body that runs once instead would be silently wrong."
    } else {
        "The straight-line WGSL backend handles let bindings, assignments, \
         arithmetic, comparisons, casts and prelude builtins only."
    };
    CodegenError::UnsupportedFeature(format!(
        "{kind} at line {} is not supported by the straight-line WGSL backend. {why}",
        expr.span.line
    ))
}

fn emit_function(out: &mut String, func: &Function) -> CodegenResult<()> {
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| {
            let ty = wgsl_type(&p.ty.kind).ok_or_else(|| {
                CodegenError::TypeLoweringError(format!(
                    "parameter `{}` has type `{}`, which has no WGSL equivalent",
                    p.name.name,
                    type_kind_name(&p.ty.kind)
                ))
            })?;
            Ok(format!("{}: {ty}", sanitize(&p.name.name)))
        })
        .collect::<CodegenResult<Vec<_>>>()?;

    let ret = match &func.ret_ty {
        Some(t) => {
            let ty = wgsl_type(&t.kind).ok_or_else(|| {
                CodegenError::TypeLoweringError(format!(
                    "return type `{}` has no WGSL equivalent",
                    type_kind_name(&t.kind)
                ))
            })?;
            format!(" -> {ty}")
        }
        None => String::new(),
    };

    out.push_str(&format!(
        "fn {}({}){ret} {{\n",
        sanitize(&func.name.name),
        params.join(", ")
    ));

    for stmt in &func.body.stmts {
        emit_stmt(out, stmt, 1)?;
    }
    if let Some(tail) = &func.body.expr {
        // A block ending in `return ...` needs no extra return after it.
        if matches!(tail.kind, ExprKind::Return(_)) {
            emit_expr_inline(out, tail);
            out.push_str(";\n");
        } else {
            emit_expr_inline(out, tail);
            out.push_str(";\n    return;\n");
        }
    }

    out.push_str("}\n\n");
    Ok(())
}

fn emit_stmt(out: &mut String, stmt: &Stmt, depth: usize) -> CodegenResult<()> {
    let pad = "    ".repeat(depth);
    match &stmt.kind {
        StmtKind::Let(s) => {
            out.push_str(&pad);
            out.push_str(&format!("let {} = ", sanitize(&pattern_name(&s.pattern))));
            emit_expr_inline(out, &s.value);
            out.push_str(";\n");
            Ok(())
        }
        StmtKind::LetInOut(s) => {
            out.push_str(&pad);
            out.push_str(&format!("var {} = ", sanitize(&s.name.name)));
            emit_expr_inline(out, &s.value);
            out.push_str(";\n");
            Ok(())
        }
        StmtKind::LetConsume(s) => {
            // `consume` moves; at the WGSL level it is a copy, so emit a `let`.
            out.push_str(&pad);
            out.push_str(&format!("let {} = ", sanitize(&s.name.name)));
            emit_expr_inline(out, &s.value);
            out.push_str(";\n");
            Ok(())
        }
        StmtKind::Expr(e) => {
            out.push_str(&pad);
            emit_expr_inline(out, e);
            // WGSL requires the terminator, including after `return`. A
            // trailing `return x;` followed by another ';' would be
            // `return x;;`, which the spec rejects -- but that cannot happen
            // here because this is one statement per source statement, so the
            // terminator is always written exactly once.
            out.push(';');
            out.push('\n');
            Ok(())
        }
        StmtKind::Return(e) => {
            match e {
                Some(e) => {
                    out.push_str(&pad);
                    out.push_str("return ");
                    emit_expr_inline(out, e);
                    out.push_str(";\n");
                }
                None => out.push_str(&format!("{pad}return;\n")),
            }
            Ok(())
        }
        StmtKind::Proof(_) => Ok(()),
        other => Err(CodegenError::UnsupportedFeature(format!(
            "statement `{other}` at line {} is not supported",
            stmt.span.line
        ))),
    }
}

/// Write an expression into `out` without a trailing newline.
fn emit_expr_inline(out: &mut String, expr: &Expr) {
    match &expr.kind {
        ExprKind::Literal(lit) => out.push_str(&emit_literal(lit)),
        ExprKind::Var(v) => out.push_str(&sanitize(&v.name)),
        ExprKind::Index(base, idx) => {
            emit_expr_inline(out, base);
            out.push('[');
            emit_expr_inline(out, idx);
            out.push(']');
        }
        ExprKind::Ascribe(inner, _) => emit_expr_inline(out, inner),
        ExprKind::Binary(op, lhs, rhs) => {
            // Parens everywhere: WGSL precedence rules and the AST shape do not
            // have to agree, and guessing here produces subtly wrong shaders.
            out.push('(');
            emit_expr_inline(out, lhs);
            out.push(' ');
            out.push_str(wgsl_binop(op).unwrap_or("+"));
            out.push(' ');
            emit_expr_inline(out, rhs);
            out.push(')');
        }
        ExprKind::Unary(op, inner) => {
            out.push('(');
            out.push_str(wgsl_unop(op).unwrap_or("+"));
            emit_expr_inline(out, inner);
            out.push(')');
        }
        ExprKind::Return(inner) => {
            out.push_str("return");
            if let Some(e) = inner {
                out.push(' ');
                emit_expr_inline(out, e);
            }
        }
        ExprKind::Break(_) => out.push_str("break"),
        ExprKind::Continue => out.push_str("continue"),
        ExprKind::Call(callee, args) => {
            let callee_ident = callee_name(callee);
            // Own the sanitized string so nothing is leaked and no borrow of a
            // temporary outlives the push.
            let sanitized = sanitize(&callee_ident);
            let name: &str = builtin_from_name(&callee_ident)
                .map(|b| b.wgsl)
                .unwrap_or(sanitized.as_str());
            out.push_str(name);
            out.push('(');
            for (i, a) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                emit_expr_inline(out, a);
            }
            out.push(')');
        }
        // check_expr has already rejected everything else.
        _ => out.push_str("/* unsupported */"),
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Int(i) => format!("{i}i"),
        Literal::UInt(i) => format!("{i}u"),
        Literal::Float(f) => {
            // WGSL needs an explicit fractional part or the literal is an
            // abstract float that may not convert.
            if f.fract() == 0.0 && f.is_finite() {
                format!("{f:.1}")
            } else {
                format!("{f}")
            }
        }
        Literal::Bool(b) => b.to_string(),
        Literal::Unit => "()".to_string(),
        other => format!("/* unsupported literal {other:?} */"),
    }
}

/// A prelude builtin that maps onto a WGSL builtin function.
struct Builtin {
    wgsl: &'static str,
}

/// Map a prelude builtin onto its WGSL counterpart.
///
/// Kept in exact agreement with the prelude's `math_funcs` table in
/// typecheck/mod.rs, which warns that any addition there needs a matching arm
/// here. `min` / `max` / `pow` are deliberately absent: they are not prelude
/// builtins, so a call to them never typechecks and mapping them would be
/// unreachable code implying support that does not exist.
fn builtin_from_name(name: &str) -> Option<Builtin> {
    Some(Builtin {
        wgsl: match name {
            "round" => "round",
            "abs" => "abs",
            "floor" => "floor",
            "ceil" => "ceil",
            "clamp" => "clamp",
            "exp" => "exp",
            "sqrt" => "sqrt",
            _ => return None,
        },
    })
}

fn wgsl_binop(op: &BinOp) -> Option<&'static str> {
    Some(match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        _ => return None,
    })
}

fn wgsl_unop(op: &crate::ast::UnOp) -> Option<&'static str> {
    Some(match op {
        crate::ast::UnOp::Neg => "-",
        crate::ast::UnOp::Not => "!",
        _ => return None,
    })
}

/// Map a Naso scalar type to a WGSL type.
fn wgsl_type(kind: &TypeKind) -> Option<&'static str> {
    Some(match kind {
        TypeKind::Int => "i32",
        TypeKind::UInt => "u32",
        TypeKind::Float => "f32",
        TypeKind::Bool => "bool",
        // A tensor has no WGSL equivalent in a function parameter position.
        // Plumbing them through would require deciding the whole buffer
        // layout, which is the compute-pipeline work this backend does not do.
        _ => return None,
    })
}

fn callee_name(expr: &Expr) -> String {
    match &expr.kind {
        ExprKind::Var(v) => v.name.clone(),
        _ => String::new(),
    }
}

fn pattern_name(p: &crate::ast::Pattern) -> String {
    use crate::ast::PatternKind;
    match &p.kind {
        PatternKind::Ident(i) => i.name.clone(),
        PatternKind::Wildcard => "_".to_string(),
        _ => "unsupported_pattern".to_string(),
    }
}

/// Make a Naso identifier safe as a WGSL identifier.
///
/// WGSL reserves a set of words, so a Naso parameter named `var` or `fn` would
/// produce a shader that fails to compile with a confusing error. Prefixing
/// keeps every Naso identifier usable and is trivially reversible by a reader.
fn sanitize(name: &str) -> String {
    if WGSL_RESERVED.contains(&name) {
        format!("naso_{name}")
    } else {
        name.to_string()
    }
}

/// WGSL reserved words that are plausible Naso identifiers.
const WGSL_RESERVED: &[&str] = &[
    "var",
    "let",
    "const",
    "fn",
    "struct",
    "return",
    "if",
    "else",
    "loop",
    "while",
    "for",
    "break",
    "continue",
    "switch",
    "case",
    "default",
    "discard",
    "true",
    "false",
    "override",
    "alias",
    "bitcast",
    "enable",
    "diagnostic",
    "requires",
    "workgroup",
    "storage",
    "uniform",
    "private",
    "read",
    "write",
    "read_write",
    "type",
    "mat",
    "vec",
    "ptr",
    "atomic",
];

fn type_kind_name(kind: &TypeKind) -> &'static str {
    match kind {
        TypeKind::Int => "int",
        TypeKind::UInt => "uint",
        TypeKind::Float => "float",
        TypeKind::Bool => "bool",
        TypeKind::Tensor(_) => "tensor",
        TypeKind::Array(..) => "array",
        TypeKind::Nat => "nat",
        _ => "type",
    }
}

fn describe_item(item: &Item) -> &'static str {
    match item {
        Item::Function(_) => "function",
        Item::TypeDef(_) => "type definition",
        Item::Module(_) => "module declaration",
        Item::Import(_) => "import",
        _ => "item",
    }
}

fn item_span_line(item: &Item) -> u32 {
    match item {
        Item::Function(f) => f.span.line,
        Item::TypeDef(t) => t.span.line,
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_program;

    fn lower(src: &str) -> CodegenResult<String> {
        let program = parse_program(src).expect("parse");
        generate_wgsl_straight_line(&program)
    }

    #[test]
    fn test_straight_line_arithmetic() {
        let wgsl = lower("fn add(a: float, b: float) -> float { return a + b; }").unwrap();
        assert!(wgsl.contains("fn add(a: f32, b: f32) -> f32"), "{wgsl}");
        assert!(wgsl.contains("    return"), "indented: {wgsl}");
        assert!(wgsl.contains("return (a + b)"), "{wgsl}");
    }

    #[test]
    fn test_let_binding_and_builtins() {
        let wgsl = lower(
            "fn f(x: float) -> float { let y = abs(x) + round(x); return clamp(y, 0.0, 1.0); }",
        )
        .unwrap();
        assert!(wgsl.contains("let y = "), "{wgsl}");
        assert!(wgsl.contains("abs(x)"), "{wgsl}");
        assert!(wgsl.contains("round(x)"), "{wgsl}");
        assert!(wgsl.contains("clamp("), "{wgsl}");
    }

    /// Float literals must keep a fractional part or WGSL may treat them as
    /// abstract floats that do not convert to f32.
    #[test]
    fn test_float_literals_are_wgsl_valid() {
        let wgsl = lower("fn f() -> float { return 1.0; }").unwrap();
        assert!(wgsl.contains("1.0"), "got {wgsl}");
        assert!(!wgsl.contains("1.0f"), "no trailing f32 suffix: {wgsl}");
    }

    /// A Naso parameter named `var` must not produce a shader that fails to
    /// compile. Reserved words are prefixed.
    #[test]
    fn test_reserved_identifiers_are_renamed() {
        let wgsl = lower("fn f(var: float) -> float { return var; }").unwrap();
        assert!(wgsl.contains("naso_var"), "{wgsl}");
        assert!(!wgsl.contains(": float)"), "{wgsl}");
    }

    /// The central property: a loop is REFUSED, not silently emitted as a
    /// body that runs once.
    #[test]
    fn test_forall_loop_is_rejected_not_silently_dropped() {
        let err = lower("fn f(t: Tensor[float, 4]) { forall i in 0..4 { t[i] = 1.0; } }")
            .expect_err("must reject a loop");
        let msg = err.to_string();
        assert!(msg.contains("forall"), "{msg}");
        assert!(msg.contains("not supported"), "{msg}");
    }

    #[test]
    fn test_while_loop_is_rejected() {
        let err = lower("fn f() -> int { let n = 0; while n < 4 { n = n + 1; } return n; }")
            .expect_err("must reject");
        assert!(err.to_string().contains("not supported"), "{err}");
    }

    /// A proof block is erased, so it must not appear in the shader and must
    /// not block emission.
    #[test]
    fn test_proof_block_is_erased() {
        let wgsl =
            lower("fn f(n: int) -> int { proof { assert(n + 0 == n); } return n + 1; }").unwrap();
        assert!(
            !wgsl.contains("assert"),
            "proof must not be emitted: {wgsl}"
        );
        assert!(wgsl.contains("return (n + 1i)"), "{wgsl}");
    }

    /// A rejected function must abort the WHOLE program, so a partial shader is
    /// never written.
    #[test]
    fn test_unsupported_function_aborts_entire_program() {
        let err = lower(
            "fn good(a: float) -> float { return a; }
             fn bad(t: Tensor[float, 4]) { forall i in 0..4 { t[i] = 1.0; } }",
        )
        .expect_err("must reject the program");
        assert!(err.to_string().contains("not supported"), "{err}");
    }

    /// An unknown call must error. The older generator emitted a comment.
    #[test]
    fn test_unknown_call_is_rejected() {
        let err = lower("fn f(x: float) -> float { return mystery(x); }")
            .expect_err("must reject unknown call");
        assert!(err.to_string().contains("not supported"), "{err}");
    }

    /// A call to another Naso function is refused, but by NAME. Emitting the
    /// callee is easy -- it is already emitted as a WGSL fn -- so the message
    /// A call to another function in the program is emitted.
    ///
    /// WGSL has no forward declarations, so a callee must appear before its
    /// caller even when the source lists the caller first.
    #[test]
    fn test_cross_function_call_is_emitted_callee_first() {
        let wgsl = lower(
            "fn outer(x: float) -> float { return inner(x) * 2.0; }\nfn inner(x: float) -> float { return round(x); }",
        )
        .unwrap();
        let inner_at = wgsl.find("fn inner").expect("inner emitted");
        let outer_at = wgsl.find("fn outer").expect("outer emitted");
        assert!(
            inner_at < outer_at,
            "callee must be declared first:\n{wgsl}"
        );
        assert!(wgsl.contains("(inner(x) * 2.0)"), "{wgsl}");
    }

    /// Every callee precedes its caller, across a scrambled 6-function chain.
    #[test]
    fn test_declaration_order_respects_all_dependencies() {
        let wgsl = lower(
            "fn f6(x: int) -> int { return f1(x); }\nfn f3(x: int) -> int { return f4(x); }\nfn f1(x: int) -> int { return f2(x); }\nfn f5(x: int) -> int { return f6(x); }\nfn f2(x: int) -> int { return x; }\nfn f4(x: int) -> int { return f5(x); }",
        )
        .unwrap();
        let at = |n: &str| {
            wgsl.find(&format!("fn {n}"))
                .unwrap_or_else(|| panic!("{n} missing\n{wgsl}"))
        };
        for (caller, callee) in [
            ("f6", "f1"),
            ("f1", "f2"),
            ("f3", "f4"),
            ("f4", "f5"),
            ("f5", "f6"),
        ] {
            assert!(
                at(callee) < at(caller),
                "{callee} must precede {caller}\n{wgsl}"
            );
        }
    }

    /// Recursion has no valid WGSL form. The typechecker accepts `fn f(x) {
    /// f(x) }` today, so the backend must refuse rather than emit something
    /// that fails to compile.
    #[test]
    fn test_self_recursion_is_rejected() {
        let err =
            lower("fn f(x: int) -> int { return f(x) + 1; }").expect_err("must reject recursion");
        assert!(err.to_string().contains("recursive call to `f`"), "{err}");
    }

    #[test]
    fn test_mutual_recursion_is_rejected() {
        let err =
            lower("fn a(x: int) -> int { return b(x); }\nfn b(x: int) -> int { return a(x); }")
                .expect_err("must reject mutual recursion");
        let msg = err.to_string();
        assert!(msg.contains("recursive call"), "{msg}");
        assert!(msg.contains("Mutual recursion"), "{msg}");
    }

    /// A wrong argument count is a diagnostic, not invalid WGSL. The
    /// typechecker catches this first in practice, but the backend must not
    /// rely on that: `lower` bypasses check_program.
    #[test]
    fn test_call_arity_is_checked() {
        let err =
            lower("fn a(x: int) -> int { return x + 1; }\nfn b(x: int) -> int { return a(); }")
                .expect_err("must reject wrong arity");
        assert!(err.to_string().contains("passes 0 argument"), "{err}");
    }

    #[test]
    fn test_conditional_is_rejected() {
        let err = lower("fn f(a: int) -> int { if a > 0 { return 1; } return 0; }")
            .expect_err("must reject if");
        assert!(err.to_string().contains("not supported"), "{err}");
    }

    /// WGSL requires a `;` after every statement. This shipped broken once --
    /// `return round(clamped)` with no terminator -- and nothing caught it
    /// because the assertions only checked for substrings.
    #[test]
    fn test_every_statement_is_terminated() {
        let wgsl = lower(
            "fn f(a: float, b: float) -> float { let x = a * 2.0; let y = clamp(x, 0.0, b); return round(y); }",
        )
        .unwrap();
        for line in wgsl.lines() {
            let t = line.trim();
            if t.is_empty() || t.ends_with('{') || t.ends_with('}') || t.starts_with("//") {
                continue;
            }
            assert!(
                t.ends_with(';'),
                "unterminated WGSL statement: {t:?}\n{wgsl}"
            );
        }
    }

    /// Precedence must be parenthesised rather than assumed.
    #[test]
    fn test_expressions_are_parenthesised() {
        let wgsl = lower("fn f(a: int, b: int, c: int) -> int { return a + b * c; }").unwrap();
        assert!(wgsl.contains("(a + (b * c))"), "{wgsl}");
    }
}
