//! Straight-line WGSL code generation.
//!
//! This is the deliberately narrow WGSL backend. It handles straight-line code
//! -- let bindings, assignments, arithmetic, comparisons, the numeric builtins
//! the prelude declares, and casts -- and produces a `fn` per Naso function.
//!
//! # Why this is separate from [`super::wgsl`]
//!
//! The existing generator works from PIR and dispatches on two hardcoded
//! function names, `quantize_int8_symmetric` and `dequantize_int8_symmetric`.
//! Anything else becomes a `// Unknown call` comment in the output: a silent
//! no-op where the user asked for a shader. That is the failure mode this
//! module exists to avoid, so here every construct that is not handled is a
//! `CodegenError` naming the construct and its span.
//!
//! # Why no loops
//!
//! Loops require polyhedral loop lowering, which is not implemented --
//! `lower_affine_expr` in the LLVM path returns only the constant and discards
//! every coefficient. Rather than emit a shader that silently runs the body
//! once, `for` / `forall` / `while` are rejected with a message that says so.
//! A parallel `forall` does not have a correct lowering, so refusing is the
//! only sound option.
//!
//! The practical effect: a WGSL `fn` is generated, but not a compute pipeline
//! entry point. Dispatching over a tensor is not expressible without the loop
//! lowering. That is stated at the call site rather than hidden.

use crate::ast::{
    BinOp, Expr, ExprKind, Function, Item, Literal, Program, Stmt, StmtKind, TypeKind,
};
use crate::codegen::error::{CodegenError, CodegenResult};

/// Lower a program to WGSL.
///
/// Errors rather than emitting a partial shader: any function containing a
/// construct this backend does not implement aborts the whole emission.
pub fn generate_wgsl_straight_line(program: &Program) -> CodegenResult<String> {
    let mut out = String::new();
    out.push_str("// Generated by Naso -- straight-line WGSL backend\n");
    out.push_str("// Loops are not lowered yet; functions containing them are rejected.\n\n");

    // Names of every function in the program, so a call to one can be
    // reported as such rather than as an unknown callee.
    let function_names: Vec<String> = program
        .items
        .iter()
        .filter_map(|i| match i {
            Item::Function(f) => Some(f.name.name.clone()),
            _ => None,
        })
        .collect();

    let mut emitted = 0usize;
    for item in &program.items {
        let Item::Function(func) = item else {
            return Err(CodegenError::UnsupportedFeature(format!(
                "straight-line WGSL only supports function definitions, found \
                 {} at line {}",
                describe_item(item),
                item_span_line(item)
            )));
        };
        // Reject the whole program before emitting anything, so a failure
        // never leaves a truncated shader on disk.
        check_supported(func, &function_names)?;
        emit_function(&mut out, func)?;
        emitted += 1;
    }

    if emitted == 0 {
        return Err(CodegenError::UnsupportedFeature(
            "no function definitions to lower to WGSL".to_string(),
        ));
    }
    Ok(out)
}

/// Reject any function containing a construct this backend cannot emit.
fn check_supported(func: &Function, function_names: &[String]) -> CodegenResult<()> {
    let known_function_names: Vec<&str> = function_names.iter().map(|s| s.as_str()).collect();
    for stmt in &func.body.stmts {
        check_stmt(stmt, &known_function_names)?;
    }
    if let Some(tail) = &func.body.expr {
        check_expr(tail, &known_function_names)?;
    }
    Ok(())
}

fn check_stmt(stmt: &Stmt, known_function_names: &[&str]) -> CodegenResult<()> {
    match &stmt.kind {
        StmtKind::Let(s) => check_expr(&s.value, known_function_names)?,
        StmtKind::LetInOut(s) => check_expr(&s.value, known_function_names)?,
        StmtKind::LetConsume(s) => check_expr(&s.value, known_function_names)?,
        StmtKind::Expr(e) => check_expr(e, known_function_names)?,
        StmtKind::Return(e) => {
            if let Some(e) = e {
                check_expr(e, known_function_names)?;
            }
        }
        // Proof blocks are erased: they produce no runtime code and so
        // correctly contribute nothing to the shader.
        StmtKind::Proof(_) => {}
        other => {
            return Err(CodegenError::UnsupportedFeature(format!(
                "statement `{other}` at line {} is not supported by the \
                 straight-line WGSL backend",
                stmt.span.line
            )));
        }
    }
    Ok(())
}

fn check_expr(expr: &Expr, known_function_names: &[&str]) -> CodegenResult<()> {
    match &expr.kind {
        ExprKind::Literal(_) | ExprKind::Var(_) | ExprKind::Index(..) => Ok(()),
        ExprKind::Block(b) => {
            for s in &b.stmts {
                check_stmt(s, known_function_names)?;
            }
            if let Some(e) = &b.expr {
                check_expr(e, known_function_names)?;
            }
            Ok(())
        }
        ExprKind::Assign(lhs, rhs) => {
            check_expr(lhs, known_function_names)?;
            check_expr(rhs, known_function_names)
        }
        ExprKind::Ascribe(inner, _) => check_expr(inner, known_function_names),
        // `return` is an expression in this AST, and `naso parse` shows it
        // under ExprKind::Return rather than StmtKind::Return.
        ExprKind::Return(inner) => {
            if let Some(e) = inner {
                check_expr(e, known_function_names)?;
            }
            Ok(())
        }
        ExprKind::Break(inner) => {
            if let Some(e) = inner {
                check_expr(e, known_function_names)?;
            }
            Ok(())
        }
        ExprKind::Continue => Ok(()),
        ExprKind::Call(callee, args) => {
            check_expr(callee, known_function_names)?;
            for a in args {
                check_expr(a, known_function_names)?;
            }
            if builtin_from_name(&callee_name(callee)).is_some() {
                return Ok(());
            }
            // Distinguish a call to a Naso function from a call to nothing.
            // Both are unsupported, but only the first is plausibly a user
            // mistake worth naming.
            let name = callee_name(callee);
            if !name.is_empty() && known_function_names.contains(&name.as_str()) {
                return Err(CodegenError::UnsupportedFeature(format!(
                    "call to function `{name}` at line {} is not supported yet: \
                     only calls to prelude builtins are lowered. Emitting the \
                     callee as a WGSL function, and its body first, is \
                     straightforward but is not implemented.",
                    expr.span.line
                )));
            }
            Err(unsupported_expr(expr))
        }
        ExprKind::Binary(op, lhs, rhs) => {
            if wgsl_binop(op).is_none() {
                return Err(CodegenError::UnsupportedFeature(format!(
                    "operator `{op:?}` at line {} has no WGSL lowering",
                    expr.span.line
                )));
            }
            check_expr(lhs, known_function_names)?;
            check_expr(rhs, known_function_names)
        }
        ExprKind::Unary(op, inner) => {
            if wgsl_unop(op).is_none() {
                return Err(CodegenError::UnsupportedFeature(format!(
                    "unary operator `{op:?}` at line {} has no WGSL lowering",
                    expr.span.line
                )));
            }
            check_expr(inner, known_function_names)
        }
        _ => Err(unsupported_expr(expr)),
    }
}

fn unsupported_expr(expr: &Expr) -> CodegenError {
    let kind = match &expr.kind {
        ExprKind::Forall(_) => "forall loop",
        ExprKind::For(_) => "for loop",
        ExprKind::While(..) => "while loop",
        ExprKind::Match(..) => "match",
        ExprKind::If(..) => "if",
        ExprKind::Quantified(_) => "quantified proposition (proof-only, outside a proof block)",
        _ => "expression",
    };
    let why = if kind.contains("loop") {
        "Loops need polyhedral lowering, which is not implemented; emitting a \
         body that runs once instead would be silently wrong."
    } else {
        "The straight-line WGSL backend handles let bindings, assignments, \
         arithmetic, comparisons, casts and prelude builtins only."
    };
    CodegenError::UnsupportedFeature(format!(
        "{kind} at line {} is not supported by the straight-line WGSL backend. {why}",
        expr.span.line
    ))
}

fn emit_function(out: &mut String, func: &Function) -> CodegenResult<()> {
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| {
            let ty = wgsl_type(&p.ty.kind).ok_or_else(|| {
                CodegenError::TypeLoweringError(format!(
                    "parameter `{}` has type `{}`, which has no WGSL equivalent",
                    p.name.name,
                    type_kind_name(&p.ty.kind)
                ))
            })?;
            Ok(format!("{}: {ty}", sanitize(&p.name.name)))
        })
        .collect::<CodegenResult<Vec<_>>>()?;

    let ret = match &func.ret_ty {
        Some(t) => {
            let ty = wgsl_type(&t.kind).ok_or_else(|| {
                CodegenError::TypeLoweringError(format!(
                    "return type `{}` has no WGSL equivalent",
                    type_kind_name(&t.kind)
                ))
            })?;
            format!(" -> {ty}")
        }
        None => String::new(),
    };

    out.push_str(&format!(
        "fn {}({}){ret} {{\n",
        sanitize(&func.name.name),
        params.join(", ")
    ));

    for stmt in &func.body.stmts {
        emit_stmt(out, stmt, 1)?;
    }
    if let Some(tail) = &func.body.expr {
        // A block ending in `return ...` needs no extra return after it.
        if matches!(tail.kind, ExprKind::Return(_)) {
            emit_expr_inline(out, tail);
            out.push_str(";\n");
        } else {
            emit_expr_inline(out, tail);
            out.push_str(";\n    return;\n");
        }
    }

    out.push_str("}\n\n");
    Ok(())
}

fn emit_stmt(out: &mut String, stmt: &Stmt, depth: usize) -> CodegenResult<()> {
    let pad = "    ".repeat(depth);
    match &stmt.kind {
        StmtKind::Let(s) => {
            out.push_str(&pad);
            out.push_str(&format!("let {} = ", sanitize(&pattern_name(&s.pattern))));
            emit_expr_inline(out, &s.value);
            out.push_str(";\n");
            Ok(())
        }
        StmtKind::LetInOut(s) => {
            out.push_str(&pad);
            out.push_str(&format!("var {} = ", sanitize(&s.name.name)));
            emit_expr_inline(out, &s.value);
            out.push_str(";\n");
            Ok(())
        }
        StmtKind::LetConsume(s) => {
            // `consume` moves; at the WGSL level it is a copy, so emit a `let`.
            out.push_str(&pad);
            out.push_str(&format!("let {} = ", sanitize(&s.name.name)));
            emit_expr_inline(out, &s.value);
            out.push_str(";\n");
            Ok(())
        }
        StmtKind::Expr(e) => {
            out.push_str(&pad);
            emit_expr_inline(out, e);
            // WGSL requires the terminator, including after `return`. A
            // trailing `return x;` followed by another ';' would be
            // `return x;;`, which the spec rejects -- but that cannot happen
            // here because this is one statement per source statement, so the
            // terminator is always written exactly once.
            out.push(';');
            out.push('\n');
            Ok(())
        }
        StmtKind::Return(e) => {
            match e {
                Some(e) => {
                    out.push_str(&pad);
                    out.push_str("return ");
                    emit_expr_inline(out, e);
                    out.push_str(";\n");
                }
                None => out.push_str(&format!("{pad}return;\n")),
            }
            Ok(())
        }
        StmtKind::Proof(_) => Ok(()),
        other => Err(CodegenError::UnsupportedFeature(format!(
            "statement `{other}` at line {} is not supported",
            stmt.span.line
        ))),
    }
}

/// Write an expression into `out` without a trailing newline.
fn emit_expr_inline(out: &mut String, expr: &Expr) {
    match &expr.kind {
        ExprKind::Literal(lit) => out.push_str(&emit_literal(lit)),
        ExprKind::Var(v) => out.push_str(&sanitize(&v.name)),
        ExprKind::Index(base, idx) => {
            emit_expr_inline(out, base);
            out.push('[');
            emit_expr_inline(out, idx);
            out.push(']');
        }
        ExprKind::Ascribe(inner, _) => emit_expr_inline(out, inner),
        ExprKind::Binary(op, lhs, rhs) => {
            // Parens everywhere: WGSL precedence rules and the AST shape do not
            // have to agree, and guessing here produces subtly wrong shaders.
            out.push('(');
            emit_expr_inline(out, lhs);
            out.push(' ');
            out.push_str(wgsl_binop(op).unwrap_or("+"));
            out.push(' ');
            emit_expr_inline(out, rhs);
            out.push(')');
        }
        ExprKind::Unary(op, inner) => {
            out.push('(');
            out.push_str(wgsl_unop(op).unwrap_or("+"));
            emit_expr_inline(out, inner);
            out.push(')');
        }
        ExprKind::Return(inner) => {
            out.push_str("return");
            if let Some(e) = inner {
                out.push(' ');
                emit_expr_inline(out, e);
            }
        }
        ExprKind::Break(_) => out.push_str("break"),
        ExprKind::Continue => out.push_str("continue"),
        ExprKind::Call(callee, args) => {
            let callee_ident = callee_name(callee);
            // Own the sanitized string so nothing is leaked and no borrow of a
            // temporary outlives the push.
            let sanitized = sanitize(&callee_ident);
            let name: &str = builtin_from_name(&callee_ident)
                .map(|b| b.wgsl)
                .unwrap_or(sanitized.as_str());
            out.push_str(name);
            out.push('(');
            for (i, a) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                emit_expr_inline(out, a);
            }
            out.push(')');
        }
        // check_expr has already rejected everything else.
        _ => out.push_str("/* unsupported */"),
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Int(i) => format!("{i}i"),
        Literal::UInt(i) => format!("{i}u"),
        Literal::Float(f) => {
            // WGSL needs an explicit fractional part or the literal is an
            // abstract float that may not convert.
            if f.fract() == 0.0 && f.is_finite() {
                format!("{f:.1}")
            } else {
                format!("{f}")
            }
        }
        Literal::Bool(b) => b.to_string(),
        Literal::Unit => "()".to_string(),
        other => format!("/* unsupported literal {other:?} */"),
    }
}

/// A prelude builtin that maps onto a WGSL builtin function.
struct Builtin {
    wgsl: &'static str,
}

/// Map a prelude builtin onto its WGSL counterpart.
///
/// Kept in exact agreement with the prelude's `math_funcs` table in
/// typecheck/mod.rs, which warns that any addition there needs a matching arm
/// here. `min` / `max` / `pow` are deliberately absent: they are not prelude
/// builtins, so a call to them never typechecks and mapping them would be
/// unreachable code implying support that does not exist.
fn builtin_from_name(name: &str) -> Option<Builtin> {
    Some(Builtin {
        wgsl: match name {
            "round" => "round",
            "abs" => "abs",
            "floor" => "floor",
            "ceil" => "ceil",
            "clamp" => "clamp",
            "exp" => "exp",
            "sqrt" => "sqrt",
            _ => return None,
        },
    })
}

fn wgsl_binop(op: &BinOp) -> Option<&'static str> {
    Some(match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        _ => return None,
    })
}

fn wgsl_unop(op: &crate::ast::UnOp) -> Option<&'static str> {
    Some(match op {
        crate::ast::UnOp::Neg => "-",
        crate::ast::UnOp::Not => "!",
        _ => return None,
    })
}

/// Map a Naso scalar type to a WGSL type.
fn wgsl_type(kind: &TypeKind) -> Option<&'static str> {
    Some(match kind {
        TypeKind::Int => "i32",
        TypeKind::UInt => "u32",
        TypeKind::Float => "f32",
        TypeKind::Bool => "bool",
        // A tensor has no WGSL equivalent in a function parameter position.
        // Plumbing them through would require deciding the whole buffer
        // layout, which is the compute-pipeline work this backend does not do.
        _ => return None,
    })
}

fn callee_name(expr: &Expr) -> String {
    match &expr.kind {
        ExprKind::Var(v) => v.name.clone(),
        _ => String::new(),
    }
}

fn pattern_name(p: &crate::ast::Pattern) -> String {
    use crate::ast::PatternKind;
    match &p.kind {
        PatternKind::Ident(i) => i.name.clone(),
        PatternKind::Wildcard => "_".to_string(),
        _ => "unsupported_pattern".to_string(),
    }
}

/// Make a Naso identifier safe as a WGSL identifier.
///
/// WGSL reserves a set of words, so a Naso parameter named `var` or `fn` would
/// produce a shader that fails to compile with a confusing error. Prefixing
/// keeps every Naso identifier usable and is trivially reversible by a reader.
fn sanitize(name: &str) -> String {
    if WGSL_RESERVED.contains(&name) {
        format!("naso_{name}")
    } else {
        name.to_string()
    }
}

/// WGSL reserved words that are plausible Naso identifiers.
const WGSL_RESERVED: &[&str] = &[
    "var",
    "let",
    "const",
    "fn",
    "struct",
    "return",
    "if",
    "else",
    "loop",
    "while",
    "for",
    "break",
    "continue",
    "switch",
    "case",
    "default",
    "discard",
    "true",
    "false",
    "override",
    "alias",
    "bitcast",
    "enable",
    "diagnostic",
    "requires",
    "workgroup",
    "storage",
    "uniform",
    "private",
    "read",
    "write",
    "read_write",
    "type",
    "mat",
    "vec",
    "ptr",
    "atomic",
];

fn type_kind_name(kind: &TypeKind) -> &'static str {
    match kind {
        TypeKind::Int => "int",
        TypeKind::UInt => "uint",
        TypeKind::Float => "float",
        TypeKind::Bool => "bool",
        TypeKind::Tensor(_) => "tensor",
        TypeKind::Array(..) => "array",
        TypeKind::Nat => "nat",
        _ => "type",
    }
}

fn describe_item(item: &Item) -> &'static str {
    match item {
        Item::Function(_) => "function",
        Item::TypeDef(_) => "type definition",
        Item::Module(_) => "module declaration",
        Item::Import(_) => "import",
        _ => "item",
    }
}

fn item_span_line(item: &Item) -> u32 {
    match item {
        Item::Function(f) => f.span.line,
        Item::TypeDef(t) => t.span.line,
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_program;

    fn lower(src: &str) -> CodegenResult<String> {
        let program = parse_program(src).expect("parse");
        generate_wgsl_straight_line(&program)
    }

    #[test]
    fn test_straight_line_arithmetic() {
        let wgsl = lower("fn add(a: float, b: float) -> float { return a + b; }").unwrap();
        assert!(wgsl.contains("fn add(a: f32, b: f32) -> f32"), "{wgsl}");
        assert!(wgsl.contains("    return"), "indented: {wgsl}");
        assert!(wgsl.contains("return (a + b)"), "{wgsl}");
    }

    #[test]
    fn test_let_binding_and_builtins() {
        let wgsl = lower(
            "fn f(x: float) -> float { let y = abs(x) + round(x); return clamp(y, 0.0, 1.0); }",
        )
        .unwrap();
        assert!(wgsl.contains("let y = "), "{wgsl}");
        assert!(wgsl.contains("abs(x)"), "{wgsl}");
        assert!(wgsl.contains("round(x)"), "{wgsl}");
        assert!(wgsl.contains("clamp("), "{wgsl}");
    }

    /// Float literals must keep a fractional part or WGSL may treat them as
    /// abstract floats that do not convert to f32.
    #[test]
    fn test_float_literals_are_wgsl_valid() {
        let wgsl = lower("fn f() -> float { return 1.0; }").unwrap();
        assert!(wgsl.contains("1.0"), "got {wgsl}");
        assert!(!wgsl.contains("1.0f"), "no trailing f32 suffix: {wgsl}");
    }

    /// A Naso parameter named `var` must not produce a shader that fails to
    /// compile. Reserved words are prefixed.
    #[test]
    fn test_reserved_identifiers_are_renamed() {
        let wgsl = lower("fn f(var: float) -> float { return var; }").unwrap();
        assert!(wgsl.contains("naso_var"), "{wgsl}");
        assert!(!wgsl.contains(": float)"), "{wgsl}");
    }

    /// The central property: a loop is REFUSED, not silently emitted as a
    /// body that runs once.
    #[test]
    fn test_forall_loop_is_rejected_not_silently_dropped() {
        let err = lower("fn f(t: Tensor[float, 4]) { forall i in 0..4 { t[i] = 1.0; } }")
            .expect_err("must reject a loop");
        let msg = err.to_string();
        assert!(msg.contains("forall"), "{msg}");
        assert!(msg.contains("not supported"), "{msg}");
    }

    #[test]
    fn test_while_loop_is_rejected() {
        let err = lower("fn f() -> int { let n = 0; while n < 4 { n = n + 1; } return n; }")
            .expect_err("must reject");
        assert!(err.to_string().contains("not supported"), "{err}");
    }

    /// A proof block is erased, so it must not appear in the shader and must
    /// not block emission.
    #[test]
    fn test_proof_block_is_erased() {
        let wgsl =
            lower("fn f(n: int) -> int { proof { assert(n + 0 == n); } return n + 1; }").unwrap();
        assert!(
            !wgsl.contains("assert"),
            "proof must not be emitted: {wgsl}"
        );
        assert!(wgsl.contains("return (n + 1i)"), "{wgsl}");
    }

    /// A rejected function must abort the WHOLE program, so a partial shader is
    /// never written.
    #[test]
    fn test_unsupported_function_aborts_entire_program() {
        let err = lower(
            "fn good(a: float) -> float { return a; }
             fn bad(t: Tensor[float, 4]) { forall i in 0..4 { t[i] = 1.0; } }",
        )
        .expect_err("must reject the program");
        assert!(err.to_string().contains("not supported"), "{err}");
    }

    /// An unknown call must error. The older generator emitted a comment.
    #[test]
    fn test_unknown_call_is_rejected() {
        let err = lower("fn f(x: float) -> float { return mystery(x); }")
            .expect_err("must reject unknown call");
        assert!(err.to_string().contains("not supported"), "{err}");
    }

    /// A call to another Naso function is refused, but by NAME. Emitting the
    /// callee is easy -- it is already emitted as a WGSL fn -- so the message
    /// names it rather than reporting an unknown expression.
    #[test]
    fn test_call_to_user_function_is_reported_by_name() {
        let err = lower(
            "fn a(x: int) -> int { return x + 1; }\nfn b(x: int) -> int { return a(x) * 2; }",
        )
        .expect_err("must reject a cross-function call");
        let msg = err.to_string();
        assert!(msg.contains("call to function `a`"), "{msg}");
        assert!(msg.contains("not supported"), "{msg}");
    }

    #[test]
    fn test_conditional_is_rejected() {
        let err = lower("fn f(a: int) -> int { if a > 0 { return 1; } return 0; }")
            .expect_err("must reject if");
        assert!(err.to_string().contains("not supported"), "{err}");
    }

    /// WGSL requires a `;` after every statement. This shipped broken once --
    /// `return round(clamped)` with no terminator -- and nothing caught it
    /// because the assertions only checked for substrings.
    #[test]
    fn test_every_statement_is_terminated() {
        let wgsl = lower(
            "fn f(a: float, b: float) -> float { let x = a * 2.0; let y = clamp(x, 0.0, b); return round(y); }",
        )
        .unwrap();
        for line in wgsl.lines() {
            let t = line.trim();
            if t.is_empty() || t.ends_with('{') || t.ends_with('}') || t.starts_with("//") {
                continue;
            }
            assert!(
                t.ends_with(';'),
                "unterminated WGSL statement: {t:?}\n{wgsl}"
            );
        }
    }

    /// Precedence must be parenthesised rather than assumed.
    #[test]
    fn test_expressions_are_parenthesised() {
        let wgsl = lower("fn f(a: int, b: int, c: int) -> int { return a + b * c; }").unwrap();
        assert!(wgsl.contains("(a + (b * c))"), "{wgsl}");
    }
}
