use crate::codegen::error::{CodegenError, CodegenResult};
use crate::ir::{
    access_relation::{AccessRelation, AccessRelations, AccessType},
    affine_domain::{AffineDomain, AffineConstraint},
    affine_map::{AffineMap, Matrix},
    pir_types::{BinaryOp, PirExpr, PirModule, PirStatement, QuantityMap},
    schedule_tree::{ScheduleNode, ScheduleTree, StmtId},
};
use crate::ast::Quantity;
use std::collections::{HashMap, HashSet};

/// WGSL code generation target
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WgslTarget {
    WebGpu,
}

/// WGSL codegen context
pub struct WgslContext {
    target: WgslTarget,
    module: PirModule,
    binding_counter: usize,
    buffer_names: HashMap<String, String>, // var name -> buffer binding name
    workgroup_size: u32,
}

impl WgslContext {
    pub fn new(module: PirModule, target: WgslTarget) -> Self {
        Self {
            target,
            module,
            binding_counter: 0,
            buffer_names: HashMap::new(),
            workgroup_size: 256,
        }
    }

    /// Generate WGSL compute shader from PIR module
    pub fn generate(&mut self) -> CodegenResult<String> {
        let mut wgsl = String::new();

        wgsl.push_str("// Generated by Naso WGSL Codegen\n");
        wgsl.push_str("// INT8 Symmetric Quantization Kernel\n\n");

        // Collect all buffers needed
        self.collect_buffers()?;

        // Emit buffer bindings
        self.emit_bindings(&mut wgsl)?;

        // Emit compute shader entry point for each statement
        for stmt in &self.module.statements {
            self.emit_compute_entry(&mut wgsl, stmt)?;
        }

        Ok(wgsl)
    }

    fn collect_buffers(&mut self) -> CodegenResult<()> {
        // Collect unique array names from accesses
        let mut arrays = HashSet::new();
        for access in &self.module.accesses.relations {
            if let Some(name) = &access.array_name {
                arrays.insert(name.clone());
            }
        }

        // Assign binding points for each array
        for array in arrays {
            let binding_name = format!("buffer_{}", self.binding_counter);
            self.buffer_names.insert(array, binding_name);
            self.binding_counter += 1;
        }

        // Handle scale parameter if present
        if self.module.quantities.contains_key("scale") {
            let binding_name = format!("buffer_{}", self.binding_counter);
            self.buffer_names.insert("scale".to_string(), binding_name);
            self.binding_counter += 1;
        }

        // Handle N parameter
        if self.module.quantities.contains_key("N") {
            let binding_name = format!("buffer_{}", self.binding_counter);
            self.buffer_names.insert("N".to_string(), binding_name);
            self.binding_counter += 1;
        }

        Ok(())
    }

    fn emit_bindings(&self, wgsl: &mut String) -> CodegenResult<()> {
        wgsl.push_str("// Buffer Bindings\n");
        wgsl.push_str("// @group(0) @binding(n) var<storage, read_write> buffer_name: array<type>;\n\n");

        let mut binding_index = 0;

        // Input/output tensor buffers
        for access in &self.module.accesses.relations {
            let array = access.array_name.as_deref().unwrap_or("mem");
            if let Some(binding_name) = self.buffer_names.get(array) {
                let (storage_class, access_mode) = match access.access_type {
                    AccessType::Read => ("read", "read"),
                    AccessType::Write => ("read_write", "write"),
                    AccessType::ReadWrite => ("read_write", "read_write"),
                    AccessType::Reduction => ("read_write", "read_write"),
                };

                // Determine element type from array name / usage
                let elem_type = self.infer_element_type(array);
                let wgsl_type = self.wgsl_type_from_element(elem_type);

                wgsl.push_str(&format!(
                    "@group(0) @binding({}) var<storage, {}> {}: array<{};\n",
                    binding_index, storage_class, binding_name, wgsl_type
                ));
                binding_index += 1;
            }
        }

        // Scale uniform buffer (read-only)
        if self.buffer_names.contains_key("scale") {
            if let Some(binding_name) = self.buffer_names.get("scale") {
                wgsl.push_str(&format!(
                    "@group(0) @binding({}) var<uniform> {}: f32;\n",
                    binding_index, binding_name
                ));
                binding_index += 1;
            }
        }

        // N parameter uniform
        if self.buffer_names.contains_key("N") {
            if let Some(binding_name) = self.buffer_names.get("N") {
                wgsl.push_str(&format!(
                    "@group(0) @binding({}) var<uniform> {}: u32;\n",
                    binding_index, binding_name
                ));
                binding_index += 1;
            }
        }

        wgsl.push('\n');
        Ok(())
    }

    fn emit_compute_entry(&self, wgsl: &mut String, stmt: &PirStatement) -> CodegenResult<()> {
        let func_name = self.infer_function_name(&stmt.body);
        
        wgsl.push_str(&format!(
            "\n// Compute entry for statement {}\n",
            stmt.id
        ));

        // Determine workgroup count based on domain
        let domain_size = self.compute_domain_size(&stmt.domain);
        
        wgsl.push_str(&format!(
            "@compute @workgroup_size({})\n",
            self.workgroup_size
        ));
        wgsl.push_str(&format!("fn {}(@builtin(global_invocation_id) global_id: vec3<u32>) {{\n", func_name));
        
        // Bounds check
        wgsl.push_str(&format!(
            "    if (global_id.x >= {}) {{ return; }}\n",
            domain_size
        ));

        // Emit body
        self.emit_expr(wgsl, &stmt.body, 1)?;

        wgsl.push_str("}\n");
        Ok(())
    }

    fn compute_domain_size(&self, domain: &AffineDomain) -> u32 {
        // For simple 1D domains, extract the upper bound
        // In practice, this would be more sophisticated
        if domain.n_iter == 1 && domain.n_param == 1 {
            // Look for constraint: -i + N >= 1 (i <= N-1)
            for c in &domain.constraints {
                if c.coefficients.len() == 2 && c.coefficients[0] == -1 && c.coefficients[1] == 1 {
                    return c.constant as u32 + 1; // N
                }
            }
        }
        // Fallback to parameter N
        1024
    }

    fn infer_function_name(&self, expr: &PirExpr) -> String {
        match expr {
            PirExpr::Call { name, .. } => format!("compute_{}", name),
            _ => "compute_main".to_string(),
        }
    }

    fn infer_element_type(&self, array: &str) -> ElementType {
        // Determine element type based on array usage
        for stmt in &self.module.statements {
            if let PirExpr::Call { name, args } = &stmt.body {
                if (name.contains("quantize") || name.contains("dequantize")) && args.len() >= 2 {
                    if let (PirExpr::Var(input), PirExpr::Var(output)) = (&args[0], &args[1]) {
                        if output == array {
                            if name.contains("quantize") {
                                return ElementType::I8; // quantize: f32 -> i8
                            } else {
                                return ElementType::F32; // dequantize: i8 -> f32
                            }
                        }
                        if input == array {
                            if name.contains("quantize") {
                                return ElementType::F32; // quantize input
                            } else {
                                return ElementType::I8; // dequantize input
                            }
                        }
                    }
                }
            }
        }
        // Default to f32
        ElementType::F32
    }

    fn wgsl_type_from_element(&self, elem: ElementType) -> &'static str {
        match elem {
            ElementType::I8 => "i32", // WGSL doesn't have i8 in storage buffers, use i32 packed
            ElementType::F32 => "f32",
            ElementType::U8 => "u32",
        }
    }

    fn emit_expr(&self, wgsl: &mut String, expr: &PirExpr, indent: usize) -> CodegenResult<()> {
        let indent_str = "    ".repeat(indent);
        
        match expr {
            PirExpr::Call { name, args } => {
                if name.contains("quantize_int8_symmetric") {
                    self.emit_quantize_call(wgsl, args, indent)?;
                } else if name.contains("dequantize_int8_symmetric") {
                    self.emit_dequantize_call(wgsl, args, indent)?;
                } else {
                    wgsl.push_str(&format!("{}// Unknown call: {}\n", indent_str, name));
                }
            }
            PirExpr::Var(v) => {
                wgsl.push_str(&format!("{}{}\n", indent_str, v));
            }
            _ => {
                wgsl.push_str(&format!("{}// Unsupported expr: {:?}\n", indent_str, expr));
            }
        }
        Ok(())
    }

    fn emit_quantize_call(
        &self,
        wgsl: &mut String,
        args: &[PirExpr],
        indent: usize,
    ) -> CodegenResult<()> {
        let indent_str = "    ".repeat(indent);
        if args.len() >= 3 {
            if let (PirExpr::Var(input), PirExpr::Var(output), PirExpr::Var(scale)) = (&args[0], &args[1], &args[2]) {
                let input_buffer = self.buffer_names.get(input).unwrap_or(&input);
                let output_buffer = self.buffer_names.get(output).unwrap_or(&output);
                let scale_buffer = self.buffer_names.get(scale).unwrap_or(&scale);

                wgsl.push_str(&format!(
                    "{}let idx = global_id.x;\n",
                    indent_str
                ));
                wgsl.push_str(&format!(
                    "{}let val = {}[idx];\n",
                    indent_str, input_buffer
                ));
                wgsl.push_str(&format!(
                    "{}let scaled = val / {};\n",
                    indent_str, scale_buffer
                ));
                wgsl.push_str(&format!(
                    "{}let rounded = round(scaled);\n",
                    indent_str
                ));
                wgsl.push_str(&format!(
                    "{}let quantized = i32(rounded);\n",
                    indent_str
                ));
                wgsl.push_str(&format!(
                    "{}{} = quantized;\n",
                    indent_str, output_buffer
                ));
            }
        }
        Ok(())
    }

    fn emit_dequantize_call(
        &self,
        wgsl: &mut String,
        args: &[PirExpr],
        indent: usize,
    ) -> CodegenResult<()> {
        let indent_str = "    ".repeat(indent);
        if args.len() >= 3 {
            if let (PirExpr::Var(input), PirExpr::Var(output), PirExpr::Var(scale)) = (&args[0], &args[1], &args[2]) {
                let input_buffer = self.buffer_names.get(input).unwrap_or(&input);
                let output_buffer = self.buffer_names.get(output).unwrap_or(&output);
                let scale_buffer = self.buffer_names.get(scale).unwrap_or(&scale);

                wgsl.push_str(&format!(
                    "{}let idx = global_id.x;\n",
                    indent_str
                ));
                wgsl.push_str(&format!(
                    "{}let val = {}[idx];\n",
                    indent_str, input_buffer
                ));
                wgsl.push_str(&format!(
                    "{}let dequantized = f32(val) * {};\n",
                    indent_str, scale_buffer
                ));
                wgsl.push_str(&format!(
                    "{}{} = dequantized;\n",
                    indent_str, output_buffer
                ));
            }
        }
        Ok(())
    }
}

/// Element types for WGSL storage buffers
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ElementType {
    I8,
    F32,
    U8,
}

/// Entry point: generate WGSL from PIR module
pub fn generate_wgsl(module: &PirModule, target: WgslTarget) -> CodegenResult<String> {
    let mut ctx = WgslContext::new(module.clone(), target);
    ctx.generate()
}

/// Verify WGSL codegen preserves QTT invariants
pub fn verify_wgsl_linearity(module: &PirModule) -> CodegenResult<()> {
    // Check that [1] quantity variables are not duplicated
    for (var, qty) in &module.quantities {
        if qty == &Quantity::One {
            let count = count_var_occurrences_in_module(module, var);
            if count != 1 {
                return Err(CodegenError::TypeLoweringError(format!(
                    "Linear variable '{}' used {} times",
                    var, count
                )));
            }
        }
    }
    Ok(())
}

fn count_var_occurrences_in_module(module: &PirModule, var: &str) -> usize {
    module
        .statements
        .iter()
        .map(|s| count_in_expr(&s.body, var))
        .sum()
}

fn count_in_expr(expr: &PirExpr, var: &str) -> usize {
    match expr {
        PirExpr::Var(v) if v == var => 1,
        PirExpr::Binary { left, right, .. } => count_in_expr(left, var) + count_in_expr(right, var),
        PirExpr::Let { value, body, .. } => count_in_expr(value, var) + count_in_expr(body, var),
        PirExpr::Unary { expr, .. } => count_in_expr(expr, var),
        PirExpr::Call { args, .. } => args.iter().map(|a| count_in_expr(a, var)).sum(),
        PirExpr::Index { base, indices } => count_in_expr(base, var) + indices.iter().map(|i| count_in_expr(i, var)).sum::<usize>(),
        PirExpr::Field { base, .. } => count_in_expr(base, var),
        PirExpr::If { cond, then_branch, else_branch } => count_in_expr(cond, var) + count_in_expr(then_branch, var) + count_in_expr(else_branch, var),
        PirExpr::Reversible { body, inverse } => count_in_expr(body, var) + count_in_expr(inverse, var),
        PirExpr::QuantumOp { op: _, args, qubits } => args.iter().map(|a| count_in_expr(a, var)).sum::<usize>() + qubits.iter().map(|q| count_in_expr(q, var)).sum::<usize>(),
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{
        access_relation::{AccessRelation, AccessRelations, AccessType},
        affine_domain::AffineDomain,
        affine_map::{AffineMap, Matrix},
        schedule_tree::{ScheduleNode, ScheduleTree},
    };
    use crate::ast::{Mutability, Quantity};
    use std::collections::HashMap;

    fn make_quant_module() -> PirModule {
        let domain = AffineDomain::new(
            1,
            1,
            vec![
                AffineConstraint::inequality(vec![1, 0], 0),
                AffineConstraint::inequality(vec![-1, 1], 1),
            ],
        ).with_name("quant_domain".to_string());

        let mut m = Matrix::new(1, 2);
        m.set(0, 0, 1);
        let schedule = AffineMap::total(domain.clone(), m.clone());

        let stmt = PirStatement {
            id: StmtId(0),
            domain: domain.clone(),
            body: PirExpr::Call {
                name: "quantize_int8_symmetric".to_string(),
                args: vec![
                    PirExpr::Var("input".to_string()),
                    PirExpr::Var("output".to_string()),
                    PirExpr::Var("scale".to_string()),
                ],
            },
            quantity: Quantity::Many,
            mutability: Mutability::Immutable,
            span: None,
        };

        let schedule_tree = ScheduleTree::new(
            ScheduleNode::band(
                vec![schedule],
                vec![false],
                ScheduleNode::domain(StmtId(0), domain.clone()),
            ),
            vec!["N".to_string()],
        );

        let mut accesses = AccessRelations::new();
        let access_map = AffineMap::total(domain.clone(), m);
        accesses.add(
            AccessRelation::new(
                StmtId(0),
                domain.clone(),
                access_map.clone(),
                AccessType::Read,
            )
            .with_array_name("input"),
        );
        accesses.add(
            AccessRelation::new(StmtId(0), domain, access_map, AccessType::Write)
                .with_array_name("output"),
        );

        let mut quantities = HashMap::new();
        quantities.insert("input".to_string(), Quantity::One);
        quantities.insert("output".to_string(), Quantity::One);
        quantities.insert("scale".to_string(), Quantity::Zero);
        quantities.insert("N".to_string(), Quantity::Zero);

        PirModule::new(
            vec![stmt],
            schedule_tree,
            accesses,
            quantities,
            vec!["N".to_string()],
        )
    }

    fn make_dequant_module() -> PirModule {
        let domain = AffineDomain::new(
            1,
            1,
            vec![
                AffineConstraint::inequality(vec![1, 0], 0),
                AffineConstraint::inequality(vec![-1, 1], 1),
            ],
        ).with_name("dequant_domain".to_string());

        let mut m = Matrix::new(1, 2);
        m.set(0, 0, 1);
        let schedule = AffineMap::total(domain.clone(), m.clone());

        let stmt = PirStatement {
            id: StmtId(0),
            domain: domain.clone(),
            body: PirExpr::Call {
                name: "dequantize_int8_symmetric".to_string(),
                args: vec![
                    PirExpr::Var("input".to_string()),
                    PirExpr::Var("output".to_string()),
                    PirExpr::Var("scale".to_string()),
                ],
            },
            quantity: Quantity::Many,
            mutability: Mutability::Immutable,
            span: None,
        };

        let schedule_tree = ScheduleTree::new(
            ScheduleNode::band(
                vec![schedule],
                vec![false],
                ScheduleNode::domain(StmtId(0), domain.clone()),
            ),
            vec!["N".to_string()],
        );

        let mut accesses = AccessRelations::new();
        let access_map = AffineMap::total(domain.clone(), m);
        accesses.add(
            AccessRelation::new(
                StmtId(0),
                domain.clone(),
                access_map.clone(),
                AccessType::Read,
            )
            .with_array_name("input"),
        );
        accesses.add(
            AccessRelation::new(StmtId(0), domain, access_map, AccessType::Write)
                .with_array_name("output"),
        );

        let mut quantities = HashMap::new();
        quantities.insert("input".to_string(), Quantity::One);
        quantities.insert("output".to_string(), Quantity::One);
        quantities.insert("scale".to_string(), Quantity::Zero);
        quantities.insert("N".to_string(), Quantity::Zero);

        PirModule::new(
            vec![stmt],
            schedule_tree,
            accesses,
            quantities,
            vec!["N".to_string()],
        )
    }

    #[test]
    fn test_quant_wgsl_generation() {
        let module = make_quant_module();
        let result = generate_wgsl(&module, WgslTarget::WebGpu);
        assert!(result.is_ok());
        let wgsl = result.unwrap();
        assert!(wgsl.contains("@compute @workgroup_size(256)"));
        assert!(wgsl.contains("quantize_int8_symmetric"));
        assert!(wgsl.contains("buffer_"));
    }

    #[test]
    fn test_dequant_wgsl_generation() {
        let module = make_dequant_module();
        let result = generate_wgsl(&module, WgslTarget::WebGpu);
        assert!(result.is_ok());
        let wgsl = result.unwrap();
        assert!(wgsl.contains("@compute @workgroup_size(256)"));
        assert!(wgsl.contains("dequantize_int8_symmetric"));
    }

    #[test]
    fn test_linearity_preserved() {
        let module = make_quant_module();
        let result = verify_wgsl_linearity(&module);
        assert!(result.is_ok());
    }

    #[test]
    fn test_wgsl_syntax_basic() {
        let module = make_quant_module();
        let wgsl = generate_wgsl(&module, WgslTarget::WebGpu).unwrap();
        
        // Basic WGSL syntax checks
        assert!(wgsl.contains("@group(0)"));
        assert!(wgsl.contains("@binding("));
        assert!(wgsl.contains("var<storage"));
        assert!(wgsl.contains("fn compute_"));
        assert!(wgsl.contains("global_invocation_id"));
    }
}