// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/09/2026, 4:18:01 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/E/.hermes/projects/Naso/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/E/.hermes/projects/Naso/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/E/.hermes/projects/Naso/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/E/.hermes/projects/Naso/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/E/.hermes/projects/Naso/app/plugins/**/*.{js,ts,mjs}","C:/Users/E/.hermes/projects/Naso/app/composables/**/*.{js,ts,mjs}","C:/Users/E/.hermes/projects/Naso/app/utils/**/*.{js,ts,mjs}","C:/Users/E/.hermes/projects/Naso/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/E/.hermes/projects/Naso/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/E/.hermes/projects/Naso/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/E/.hermes/projects/Naso/app/app.config.{js,ts,mjs}","C:/Users/E/.hermes/projects/Naso/app/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;