//! The backend capability matrix: what each target actually accepts, measured not claimed.
//!
//! # Why this exists
//!
//! Seven defects shipped because a backend's real behaviour drifted away from what was
//! believed about it, and nothing compared the two:
//!
//! 1. QIR emitted a `Reversible` with the adjoint discarded.
//! 2. WGSL linearity did not recurse into blocks.
//! 3. WGSL wrote `// Unsupported expr` into a shader and returned success.
//! 4. `return` inside a branch was hoisted, so `guard(5)` returned `-1`.
//! 5. Cranelift returned a hardcoded `42` for every program.
//! 6. WGSL emitted a callee after its caller; the module did not parse.
//! 7. `reversible { ... }` dropped the block and generated no inverse.
//!
//! Every one reported success and exited 0. Writing a document of limitations does
//! nothing about that; the document drifts the moment the code changes.
//!
//! So the matrix below is DERIVED. Each row names a construct and what it does through
//! the real public API right now. A row that changes behaviour changes this test, which
//! fails CI. That is the drift detector.
//!
//! The matrix is generated by a companion binary-style test that writes
//! `docs/content/LIMITATIONS.md`, and a second test asserts the checked-in file matches
//! what the probes actually observed -- so the published document cannot claim more than
//! the compiler does.
//!
//! # Two rules this encodes
//!
//! - A construct is either CORRECT or REFUSED. There is no third column. "Emits
//!   something" is not an acceptable outcome for a backend that cannot lower it.
//! - "Refused" means a diagnostic naming the reason, not a comment in the output and not
//!   a placeholder value.

#![cfg(feature = "llvm")]

use naso_compiler::codegen::CodegenTarget;
use naso_compiler::codegen::llvm::module_builder::LLVMModuleBuilder;
use naso_compiler::codegen::{CodegenContext, CodegenPipeline, OptLevel};

/// What a target did with a construct.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Outcome {
    /// Accepted and lowered.
    Emits,
    /// Refused with a diagnostic.
    Refused,
}

/// One row of the matrix.
struct Row {
    /// Construct name, as it appears in the documentation.
    construct: &'static str,
    /// A minimal source program exercising it.
    src: &'static str,
    /// What the LLVM backend does.
    llvm: Outcome,
    /// Optional note on WHY, when the refusal reason is load-bearing.
    note: &'static str,
}

/// Run a construct through parse -> lower -> LLVM build, recording only whether it
/// was accepted.
///
/// Deliberately reports `Emits` only if every stage succeeded. A construct that parses
/// but fails to lower is not emitted, and a construct that lowers but fails codegen is
/// not emitted.
fn llvm_outcome(src: &str) -> Outcome {
    let Ok(program) = naso_compiler::parser::parse_program(src) else {
        return Outcome::Refused;
    };
    let Ok(pir) = naso_compiler::lowering::lower_program(&program) else {
        return Outcome::Refused;
    };
    let Ok(cc) = CodegenContext::new(CodegenTarget::Host, OptLevel::None) else {
        return Outcome::Refused;
    };
    let Ok(mut builder) = LLVMModuleBuilder::new(&cc) else {
        return Outcome::Refused;
    };
    match builder.build_module(&pir) {
        Ok(_) => Outcome::Emits,
        Err(_) => Outcome::Refused,
    }
}

/// The matrix. Every row is asserted below against the real pipeline.
fn matrix() -> Vec<Row> {
    vec![
        // -- arithmetic and control flow: the working core -----------------------
        Row {
            construct: "integer arithmetic",
            src: "fn f(a: i64, b: i64) -> i64 { a + b * 2 }",
            llvm: Outcome::Emits,
            note: "",
        },
        Row {
            construct: "float arithmetic",
            src: "fn f(a: f32, b: f32) -> f32 { a * b }",
            llvm: Outcome::Emits,
            note: "",
        },
        Row {
            construct: "`if` as an expression",
            src: "fn f(a: i64) -> i64 { if a > 0 { 1 } else { -1 } }",
            llvm: Outcome::Emits,
            note: "",
        },
        Row {
            construct: "`if` without `else`",
            src: "fn f(a: f64) -> f64 { let mut r = 0.0; if a > 0.0 { r = 1.0; } r }",
            llvm: Outcome::Emits,
            note: "",
        },
        Row {
            construct: "`while`",
            src: "fn f(n: i64) -> i64 { let mut i = 0; while i < n { i = i + 1; } i }",
            llvm: Outcome::Emits,
            note: "",
        },
        Row {
            construct: "counted `for`",
            src: "fn f(n: i64) -> i64 { let mut s = 0; for i in n { s = s + i; } s }",
            llvm: Outcome::Emits,
            note: "lowers onto the `while` CFG",
        },
        Row {
            construct: "`break`",
            src: "fn f(n: i64) -> i64 { let mut i = 0; while i < n { i = i + 1; if i > 3 { break; } } i }",
            llvm: Outcome::Emits,
            note: "",
        },
        Row {
            construct: "`continue`",
            src: "fn f(n: i64) -> i64 { let mut i = 0; while i < n { i = i + 1; if i % 2 == 0 { continue; } i = i + 1; } i }",
            llvm: Outcome::Emits,
            note: "",
        },
        Row {
            construct: "`return` inside `if`",
            src: "fn f(a: i64) -> i64 { if a > 0 { return 7; } -1 }",
            llvm: Outcome::Emits,
            note: "lowered in place, not hoisted",
        },
        Row {
            construct: "function calls",
            src: "fn g(a: i64) -> i64 { a * 2 }\nfn f(a: i64) -> i64 { g(a) + 1 }",
            llvm: Outcome::Emits,
            note: "one LLVM symbol per Naso function",
        },
        Row {
            construct: "numeric casts",
            src: "fn f(a: i64) -> i32 { a as i32 }",
            llvm: Outcome::Emits,
            note: "width-preserving, signedness-tracked",
        },
        Row {
            construct: "scalar parameters",
            src: "fn f(a: f32, b: i64) -> f32 { a }",
            llvm: Outcome::Emits,
            note: "",
        },
        Row {
            construct: "tensor parameters",
            src: "fn f(x: Tensor[f32, 8]) -> f32 { let mut s = 0.0; for j in 8 { s = s + x[j]; } s }",
            llvm: Outcome::Emits,
            note: "caller-supplied pointer plus a length",
        },
        Row {
            construct: "2-D tensors",
            src: "fn f(x: Tensor[f32, 2, 3]) -> f32 { x[1][2] }",
            llvm: Outcome::Emits,
            note: "row-major",
        },
        Row {
            construct: "quantum parameters",
            src: "fn f(q: Qubit) -> i64 { 0 }",
            llvm: Outcome::Emits,
            note: "`Qubit` and `QRegister` both map to the pointer ABI",
        },
        Row {
            construct: "symbolic loop bounds",
            src: "fn f(n: i64) -> i64 { let mut s = 0; forall i in 0..n { s = s + i; } s }",
            llvm: Outcome::Emits,
            note: "affine schedule bands",
        },
        // -- refused, with a reason ------------------------------------------------
        Row {
            construct: "`reversible { ... }`",
            src: "fn f(a: i64) -> i64 { reversible { let b = a + 1; b } }",
            llvm: Outcome::Refused,
            note: "no inverse is generated; used to drop the block and report success",
        },
        Row {
            construct: "nested tensors",
            src: "fn f(x: Tensor[Tensor[f32, 4], 8]) -> i64 { 0 }",
            llvm: Outcome::Refused,
            note: "one ptr per tensor has a single stride",
        },
        Row {
            construct: "tensor with a zero extent",
            src: "fn f(x: Tensor[f32, 0]) -> i64 { 0 }",
            llvm: Outcome::Refused,
            note: "no elements to index",
        },
        Row {
            construct: "quantity used as a type",
            src: "fn f(q: Many) -> i64 { 0 }",
            llvm: Outcome::Refused,
            note: "`Many` is a quantity; write `[1] Qubit`",
        },
        Row {
            construct: "widthless `int` parameter",
            src: "fn f(a: int) -> i64 { 0 }",
            llvm: Outcome::Refused,
            note: "no exact ABI slot without a width",
        },
        Row {
            construct: "`break` in an affine `forall` band",
            src: "fn f(n: i64) -> i64 { let mut s = 0; forall i in 0..n { if i > 3 { break; } s = s + i; } s }",
            llvm: Outcome::Refused,
            note: "the DOMAIN TRANSFORMATION is known and tested (`ir::early_exit`): a \
                   `break` at a constant prefix of the iteration shortens the band to \
                   `min(hi, k - 1)`, which stays affine, and `continue` leaves the domain \
                   alone and predicates the body. What is missing is emission of the \
                   shortened band, so the refusal stands. A guard depending on runtime data \
                   (`i >= n / 2`) has no affine answer and needs a `while` loop",
        },
        Row {
            construct: "adding two booleans",
            src: "fn f(a: bool, b: bool) -> bool { a + b }",
            llvm: Outcome::Refused,
            note: "FIXED. `unify_kinds` accepts (Bool, Bool) for `==`, and the arithmetic \
                   arm called it without asking whether the operator applied, so `true + \
                   true` reached LLVM as `add i1` and wrapped to 0. Refused by \
                   `typecheck::inference::bool_operator`",
        },
        Row {
            construct: "expression-position `reversible`",
            src: "fn f(a: i64) -> i64 { let x = reversible { a + 1 }; x }",
            llvm: Outcome::Refused,
            note: "",
        },
    ]
}

/// What the QIR backend did with a construct.
fn qir_outcome(src: &str) -> Outcome {
    let pir = match lower(src) {
        Ok(p) => p,
        Err(_) => return Outcome::Refused,
    };
    let Ok(cc) = CodegenContext::new(CodegenTarget::Host, OptLevel::None) else {
        return Outcome::Refused;
    };
    match CodegenPipeline::new(cc).emit_qir(&pir) {
        Ok(_) => Outcome::Emits,
        Err(_) => Outcome::Refused,
    }
}

/// What the straight-line WGSL backend did.
fn wgsl_straight_outcome(src: &str) -> Outcome {
    let Ok(program) = typechecked(src) else {
        return Outcome::Refused;
    };
    match naso_compiler::codegen::wgsl_straight::generate_wgsl_straight_line(&program) {
        Ok(_) => Outcome::Emits,
        Err(_) => Outcome::Refused,
    }
}

/// What the compute WGSL backend did, given the kernel name that owns the tensors.
///
/// The kernel name is a parameter, not a global, so each row states which function the
/// caller is asking to compile as a compute entry point.
fn wgsl_compute_outcome(src: &str, kernel: &str) -> Outcome {
    let Ok(program) = typechecked(src) else {
        return Outcome::Refused;
    };
    match naso_compiler::codegen::wgsl_compute::generate_wgsl_compute(&program, kernel) {
        Ok(_) => Outcome::Emits,
        Err(_) => Outcome::Refused,
    }
}

/// Parse and typecheck, which every source-level backend entry point requires.
fn typechecked(src: &str) -> Result<naso_compiler::ast::Program, String> {
    let mut program = naso_compiler::parser::parse_program(src).map_err(|e| e.to_string())?;
    let checked = naso_compiler::typecheck::check_program(&mut program);
    if !checked.errors.is_empty() {
        return Err(checked.errors[0].to_string());
    }
    Ok(checked.program)
}

/// Lower, as the PIR-level backends require.
fn lower(src: &str) -> Result<naso_compiler::ir::pir_types::PirModule, String> {
    let program = typechecked(src)?;
    naso_compiler::lowering::lower_program(&program).map_err(|e| e.to_string())
}

/// The QIR and WGSL half of the matrix.
///
/// Split out because these backends are built for a different job than LLVM and their
/// refusals are NOT the same refusals. QIR refuses every scalar computation -- it emits
/// one `void` quantum operation and has no scalar arithmetic at all -- while refusing
/// those is correct for it. Recording that as a shared row would imply QIR is a worse
/// LLVM, which it is not.
struct TargetRow {
    construct: &'static str,
    src: &'static str,
    /// Kernel name for the compute WGSL backend; unused by the others.
    kernel: &'static str,
    qir: Outcome,
    wgsl_straight: Outcome,
    wgsl_compute: Outcome,
    note: &'static str,
}

fn target_matrix() -> Vec<TargetRow> {
    vec![
        TargetRow {
            construct: "empty function",
            src: "fn f() { }",
            kernel: "f",
            qir: Outcome::Emits,
            wgsl_straight: Outcome::Emits,
            // A compute kernel with no tensor parameter has nothing to bind, so this
            // is REFUSED -- not because empty functions are unsupported, but because
            // the compute ABI is defined in terms of tensor parameters. Naming the
            // kernel that does own one is the row below.
            wgsl_compute: Outcome::Refused,
            note: "a compute kernel with no tensor parameter has nothing to bind",
        },
        // -- quantum operations: refused, and the reason is specific --------------
        //
        // These are recorded because the QIR backend's refusal here is NOT the same refusal
        // as its scalar rows. It refuses scalar arithmetic by design -- it emits one `void`
        // function per quantum operation and has no arithmetic.
        //
        // Two EARLIER defects are fixed and no longer the cause. A gate operand is BORROWED,
        // and the linearity checker no longer mistakes a borrow for a double USE;
        // `qalloc` now maps to `qir.qubit_alloc` rather than the nonexistent `qir.qalloc`.
        //
        // The refusal that remains is structural: the emitter builds one `void` function per
        // PIR statement and clears its locals between them, so a `[1]` qubit bound by
        // `qalloc` in one statement is not in scope when a later statement gates it. The
        // backend refuses rather than substituting a placeholder, because a placeholder would
        // emit valid QIR applying gates to something other than the qubit.
        //
        // LLVM accepts both programs -- its schedule tree gives every statement a place in one
        // function -- so the source language and one backend support them. The gap is
        // specific to QIR emission.
        TargetRow {
            construct: "qubit allocation and measurement",
            src: "fn f() { let [1] a: Qubit = qalloc(1); let m = measure(a); let _ = m; }",
            kernel: "f",
            qir: Outcome::Refused,
            wgsl_straight: Outcome::Refused,
            wgsl_compute: Outcome::Refused,
            note: "the measurement is in a second statement, where the qubit allocated in the first is out of scope",
        },
        TargetRow {
            construct: "a single gate",
            src: "fn f() { let [1] a: Qubit = qalloc(1); hadamard(a); let m = measure(a); let _ = m; }",
            kernel: "f",
            qir: Outcome::Refused,
            wgsl_straight: Outcome::Refused,
            wgsl_compute: Outcome::Refused,
            note: "the gate is in a second statement, where the qubit allocated in the first is out of scope",
        },
        TargetRow {
            construct: "scalar float multiply",

            src: "fn f(a: f32, b: f32) -> f32 { a * b }",
            kernel: "main",
            qir: Outcome::Refused,
            wgsl_straight: Outcome::Emits,
            wgsl_compute: Outcome::Refused,
            note: "QIR has no scalar arithmetic; it emits one void quantum operation",
        },
        TargetRow {
            construct: "scalar integer add",
            src: "fn f(a: i64) -> i64 { a + 1 }",
            kernel: "main",
            qir: Outcome::Refused,
            wgsl_straight: Outcome::Emits,
            wgsl_compute: Outcome::Refused,
            note: "",
        },
        TargetRow {
            construct: "function call",
            src: "fn g(a: f32) -> f32 { a }\nfn f(a: f32) -> f32 { g(a) }",
            kernel: "main",
            qir: Outcome::Refused,
            wgsl_straight: Outcome::Emits,
            wgsl_compute: Outcome::Refused,
            note: "",
        },
        TargetRow {
            construct: "tensor kernel entry point",
            src: "fn compute(a: Tensor[f32, 8]) { }",
            kernel: "compute",
            // QIR accepts this: it emits a void quantum operation and its parameter ABI
            // does not constrain it the way the compute WGSL ABI does. Refusing scalar
            // work in QIR above is about arithmetic, not about parameters.
            qir: Outcome::Emits,
            wgsl_straight: Outcome::Refused,
            wgsl_compute: Outcome::Emits,
            note: "the only shape the compute path accepts is a tensor-parameter kernel",
        },
        TargetRow {
            construct: "`if` in straight-line WGSL",
            src: "fn f(a: f32) -> f32 { if a > 0.0 { 1.0 } else { 0.0 } }",
            kernel: "main",
            qir: Outcome::Refused,
            wgsl_straight: Outcome::Refused,
            wgsl_compute: Outcome::Refused,
            note: "control flow has no place in a straight-line shader",
        },
        TargetRow {
            construct: "tensor subscript in straight-line WGSL",
            src: "fn f(x: Tensor[f32, 4]) -> f32 { x[0] }",
            kernel: "main",
            qir: Outcome::Refused,
            wgsl_straight: Outcome::Refused,
            wgsl_compute: Outcome::Refused,
            note: "a `tensor` type has no WGSL equivalent in that position",
        },
        TargetRow {
            construct: "assignment",
            src: "fn f(a: i64) { let mut x = a; x = 1; }",
            kernel: "f",
            qir: Outcome::Refused,
            wgsl_straight: Outcome::Emits,
            wgsl_compute: Outcome::Refused,
            note: "assignment to a `Var` is not expressible in QIR",
        },
    ]
}

/// The published line for a construct, or a panic naming what is missing.
fn published_row(construct: &str) -> String {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the compiler crate must live inside the repository")
        .join("docs/content/LIMITATIONS.md");
    let published = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{} must exist and be readable.\n{e}", path.display()));
    let marker = format!("<!-- construct:{construct} -->");
    published
        .lines()
        .find(|l| l.contains(&marker))
        .unwrap_or_else(|| {
            panic!(
                "LIMITATIONS.md is missing the row for {construct:?}.\n  expected marker: {marker}"
            )
        })
        .to_string()
}

#[test]
fn the_target_capability_matrix_matches_reality() {
    let mut wrong = Vec::new();
    for row in target_matrix() {
        for (name, expected, actual) in [
            ("QIR", row.qir, qir_outcome(row.src)),
            (
                "WGSL straight-line",
                row.wgsl_straight,
                wgsl_straight_outcome(row.src),
            ),
            (
                "WGSL compute",
                row.wgsl_compute,
                wgsl_compute_outcome(row.src, row.kernel),
            ),
        ] {
            if expected != actual {
                wrong.push(format!(
                    "{construct:?} on {name}: matrix says {expected:?}, actual is {actual:?}\n  source: {src}",
                    construct = row.construct,
                    src = row.src.replace('\n', " ")
                ));
            }
        }
    }
    assert!(
        wrong.is_empty(),
        "the target capability matrix has drifted from the compiler.\n\n{}",
        wrong.join("\n\n")
    );
}

/// A documented refusal reason must reach the published page.
///
/// Otherwise the QIR/WGSL table tells an author only THAT something is refused and not
/// why -- and for these backends the WHY is the interesting part, since refusing scalar
/// arithmetic is correct for QIR rather than a gap.
#[test]
fn every_refused_target_row_publishes_its_reason() {
    for row in target_matrix() {
        if row.note.is_empty() || row.qir != Outcome::Refused {
            continue;
        }
        let first_clause: String = row
            .note
            .split([',', '.'])
            .next()
            .unwrap_or("")
            .trim()
            .to_string();
        let line = published_row(row.construct);
        assert!(
            line.contains(&first_clause),
            "LIMITATIONS.md row for {:?} omits its documented reason {:?}.\n  row: {line}",
            row.construct,
            first_clause
        );
    }
}

/// The published QIR/WGSL section must match the target matrix.
///
/// Without this the new table is prose that drifts, which is the whole failure mode the
/// capability matrix exists to prevent. Only the constructs and the three labels are
/// checked; the note is prose and may be reworded freely.
#[test]
fn the_published_target_section_matches_the_target_matrix() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the compiler crate must live inside the repository")
        .join("docs/content/LIMITATIONS.md");
    let published = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{} must exist and be readable.\n{e}", path.display()));

    for row in target_matrix() {
        let marker = format!("<!-- construct:{} -->", row.construct);
        let line = published
            .lines()
            .find(|l| l.contains(&marker))
            .unwrap_or_else(|| {
                panic!(
                    "LIMITATIONS.md is missing {:?}. The QIR/WGSL table must list every \
                     target-matrix row.\n  expected marker: {marker}",
                    row.construct
                )
            });
        for (name, outcome) in [
            ("QIR", row.qir),
            ("WGSL straight-line", row.wgsl_straight),
            ("WGSL compute", row.wgsl_compute),
        ] {
            let label = match outcome {
                Outcome::Emits => "**emits**",
                Outcome::Refused => "**refused**",
            };
            // Count occurrences so a row that gets the right label in the wrong column
            // cannot pass by having it somewhere else in the line.
            let found = line.matches(label).count();
            let expected_count = [row.qir, row.wgsl_straight, row.wgsl_compute]
                .iter()
                .filter(|o| **o == outcome)
                .count();
            assert_eq!(
                found, expected_count,
                "LIMITATIONS.md row for {:?} shows {found} occurrence(s) of {label:?} \
                 but the matrix says {name} is {outcome:?}, so {expected_count} \
                 expected.\n  row: {line}\n\nRegenerate the document.",
                row.construct
            );
        }
    }
}

#[test]
fn the_capability_matrix_matches_reality() {
    let mut wrong = Vec::new();
    for row in matrix() {
        let actual = llvm_outcome(row.src);
        if actual != row.llvm {
            wrong.push(format!(
                "{construct:?}: matrix says {expected:?}, actual is {actual:?}\n  source: {src}",
                construct = row.construct,
                expected = row.llvm,
                src = row.src
            ));
        }
    }
    assert!(
        wrong.is_empty(),
        "the capability matrix has drifted from the compiler. Either the matrix is \
         stale, or a backend changed behaviour without anyone noticing -- which is the \
         failure mode this file exists to prevent.\n\n{}",
        wrong.join("\n\n")
    );
}

/// Every refused row must produce a diagnostic that says something.
///
/// A refusal that names no reason is not much better than a silent drop: the author
/// cannot act on it. Checked by re-running each refused construct and requiring a
/// non-empty message.
#[test]
fn every_refused_construct_names_a_reason() {
    for row in matrix().into_iter().filter(|r| r.llvm == Outcome::Refused) {
        let program = naso_compiler::parser::parse_program(row.src);
        let message: String = match program {
            Err(e) => e.to_string(),
            Ok(p) => match naso_compiler::lowering::lower_program(&p) {
                Err(e) => e.to_string(),
                Ok(pir) => {
                    let Ok(cc) = CodegenContext::new(CodegenTarget::Host, OptLevel::None) else {
                        continue;
                    };
                    let Ok(mut b) = LLVMModuleBuilder::new(&cc) else {
                        continue;
                    };
                    match b.build_module(&pir) {
                        Ok(_) => panic!(
                            "{:?} is in the matrix as Refused but built successfully",
                            row.construct
                        ),
                        Err(e) => e.to_string(),
                    }
                }
            },
        };
        assert!(
            message.trim().len() > 20,
            "{:?} was refused with a message too short to act on: {message:?}",
            row.construct
        );
    }
}

/// The published limitations document must match the matrix exactly.
///
/// Without this, `LIMITATIONS.md` is just prose that drifts. With it, changing a
/// backend's behaviour without updating the published document fails CI.
#[test]
fn the_published_limitations_document_matches_the_matrix() {
    // `CARGO_MANIFEST_DIR` is `<repo>/compiler`, so `docs/` is a SIBLING of the crate
    // root, not a child of it. Getting this wrong is the difference between "the doc is
    // missing" and "the test cannot find the doc", and only the former is a real drift.
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the compiler crate must live inside the repository")
        .join("docs/content/LIMITATIONS.md");
    let published = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{} must exist and be readable. It is generated from this matrix.\n{e}",
            path.display()
        )
    });

    for row in matrix() {
        let marker = format!("<!-- construct:{} -->", row.construct);
        assert!(
            published.contains(&marker),
            "LIMITATIONS.md is missing the row for {:?}. Regenerate it.\n\
             expected to find the marker {marker:?}",
            row.construct
        );
        // The row's documented outcome must be the measured one.
        // These are the labels LIMITATIONS.md prints, so the check compares against the
        // published text literally rather than re-interpreting it.
        let expected_label = match row.llvm {
            Outcome::Emits => "**emits**",
            Outcome::Refused => "**refused**",
        };
        let line = published
            .lines()
            .find(|l| l.contains(&marker))
            .unwrap_or_else(|| panic!("row {:?} not found", row.construct));
        // A documented reason must survive into the published page, or the page tells
        // an author only THAT something is refused and not why.
        if !row.note.is_empty() {
            let first_clause: String = row
                .note
                .split([',', '.'])
                .next()
                .unwrap_or("")
                .trim()
                .to_string();
            assert!(
                line.contains(&first_clause),
                "LIMITATIONS.md row for {:?} omits its documented reason {:?}.\n  row: {line}\n\n                 Regenerate the document.",
                row.construct,
                first_clause
            );
        }
        assert!(
            line.contains(expected_label),
            "LIMITATIONS.md says {:?} is {expected_label:?} in the matrix but the row \
             reads:\n  {line}\n\nRegenerate the document.",
            row.construct
        );
    }
}
